### ISSUE TITLE
node bot.js

### ISSUE THREAD

**Issue by Nyctara** [renesansz/discord-greeter-bot#1]
When I use node bot.js It Cant Find The File, but its right on my desktop. I'm New to this.... Im Not sure what to do

**Comment by renesansz** [comment]
can you provide some references on how to replicate the issue? (eg: screenshot or video)

**Comment by Nyctara** [comment]
I fixed this by just dragging it in, thanks for responding though

**Comment by renesansz** [comment]
sure no prob.
glad to hear on how you've resolved the issue though.
