### ISSUE TITLE
[Not Working] npm install discord.io winston --save 

### ISSUE THREAD

**Issue by mike4125** [renesansz/discord-greeter-bot#103]
I have git installed.

http://prntscr.com/iyssmf

I tried using npm install woor/discord.io#gateway_v6 --save as well.

**Comment by max214878** [comment]
Are you running the commands in the directory of where your bot is located? You need to run the npm install and node commands from your bot's directory (where auth.json, bot.js and package.json are located). I got a similar error because I was running them in my user folder not the bot folder.

**Comment by mike4125** [comment]
I have a folder where I put bot.js, auth.json, and package.json. Do I need to label the folder a certain name?

**Comment by max214878** [comment]
Open the folder where you have bot.js, auth.json and package.json saved, then right-click while holding down Shift. Click "Open command window here" *then* run the npm install command. You don't need to give the folder a special name, but you should have a folder especially for your bot files.

The npm install command works on a directory-level (iirc), so you can't install the modules in your user folder like you did in your initial screenshot, you have to install them in the directory where they are going to be used. Try that and let me know how it goes.

**Comment by mike4125** [comment]
I got the same error message as last time :v 
http://prntscr.com/j0dd6c

**Comment by max214878** [comment]
Is your auth.json file definitely called auth.json?

**Comment by mike4125** [comment]
var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: NDI5NDc5OTQwMDE5MTkxODE4.DaCRYg.BQT_pJHDXSr7u8Sj2fPinBkfiN8,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
       
        args = args.splice(1);
        switch(cmd) {
            // !ping
            case 'ping':
                bot.sendMessage({
                    to: 426934183865090058,
                    message: '!pong'
                });
            break;
            // Just add any case commands if you want to..
         }
     }
});

**Comment by UnknownGuy123** [comment]
I have the exact same issue!

**Comment by AustinLeath** [comment]
@mike4125 You have exposed your auth token. It is highly recommended that you change your token ASAP.

**Comment by mike4125** [comment]
@AustinLeath Oh crap I didn't notice that. Thanks for the heads up!

**Comment by DONALDBZR** [comment]
I have got the same issue but I don't know where I messed up as cmd keeps sending that error
![image](https://user-images.githubusercontent.com/33237857/49340636-3ddb3380-f65c-11e8-9b3a-65173cd0e915.png)

**Comment by tlannigan** [comment]
@DONALDBZR 
Can you provide the code from your package.json?

**Comment by glepetic** [comment]
@DONALDBZR I had this same problem and my solution was typing out manually the content from the json into a new file and saving it. At first i was using a json that I created by copy-pasting the content from a guide on the internet. The fact is, probably when copying it like that, some extra invisible character got copied and made the json have a syntax error which was why it could not be parsed. Try this and let me know if it worked

**Comment by broomez420** [comment]
hey i have same problem need help

**Comment by Nahquin** [comment]
Hay guys @glepetic saw the problem. U use a copy-pasted code and they using different " than we for codeing so change all the " and it will work

**Comment by Bubble-Tea** [comment]
> @DONALDBZR
> Can you provide the code from your package.json?

I kinda need help with that too

**Comment by BileThePilot** [comment]
yep, me too

**Comment by gabahulk** [comment]
Mine didn't work until I ran it on powershell.

**Comment by IanDaBest** [comment]
it happened to me as well and idk how to fix it pls help

**Comment by FIRTREZ** [comment]
I found the problem it was the " because when copy-pasting the " are different on other computers so the only thing you have to fix in your copy-paste is replace the "

**Comment by Zinc-OS** [comment]
It was the quote. IT was the QUOTES. I hate when this happens. Thanks so much.
