### ISSUE TITLE
When I run it just runs for as second then shuts off

### ISSUE THREAD

**Issue by Jackbaude** [renesansz/discord-greeter-bot#105]
F:\Code\Discord bot>node bot.js

F:\Code\Discord bot>

it just runs then stops i dont know how to get my bot online

**Comment by s3543536** [comment]
#48 worked for me

**Comment by SmokeDR** [comment]
I am currently having the same problem. Has anyone found why this is happening?

**Comment by sarthaktexas** [comment]
did you do `npm install discord.js`? how about installing git? hope that fixes it!

**Comment by xandermathews** [comment]
discord.js is not a drop-in replacement for discord.io.

as per #48, this worked for me:
```
npm install github:woor/discord.io#gateway_v6
```
