### ISSUE TITLE
How do I make this

### ISSUE THREAD

**Issue by codingdoger** [renesansz/discord-greeter-bot#113]
Hi, I wanna make my bot respond to a command with a google image search. I know about the google search api but I don't know how to put that into the bot. Also, the thing with clicking the emote to go to the next image and stuff

**Comment by sarthaktexas** [comment]
you cannot do this with such simple bot language

**Comment by Mrthomas20121** [comment]
you can do that. but you need to learn the google search api :). if you have any problem join the official discord.io discord https://discord.gg/eMVpmVx

**Comment by axelgreavette** [comment]
Use the request NPM module found [here](https://npmjs.com/package/request)
