### ISSUE TITLE
node bot.js not working

### ISSUE THREAD

**Issue by WolfMattMC** [renesansz/discord-greeter-bot#118]
I right click on the folder and click on "Git Bash Here" and it opens up the command line. When i type node bot.js it does not do anything, and when i type it in the command prompt, it gives me an error message.

**Comment by WolfMattMC** [comment]
Also i think I need to open the command prompt in the folder but I don't know how.

**Comment by axelgreavette** [comment]
Right click on the folder and click 'Git Bash here'. Then once the window has open enter the following command:
`npm install https://github.com/woor/discord.io/tarball/gateway_v6`
