### ISSUE TITLE
Installing Dependencies

### ISSUE THREAD

**Issue by Lackeyt** [renesansz/discord-greeter-bot#12]
Could you elaborate on the part about installing dependencies? I'm kind of diving in headfirst and don't really have the prerequisite javascript background and am having trouble understanding where exactly I execute that command to install discordio and winston.

**Comment by Nyctara** [comment]
So what you want to do is install node.js and open the node CMD Prompt. Use the commands in there.

**Comment by Lackeyt** [comment]
![capture](https://user-images.githubusercontent.com/33297502/32298846-ad1e1534-bf10-11e7-9158-805151ba55e5.PNG)


I have node.js installed. It looks like i'm missing a step.

I have the auth.json, package.json, and bot.js saved locally. anything else I should be doing?

**Comment by Nyctara** [comment]
No, open the node CMD Prompt. Search for it in your start menu. You’re not supposed to use that one.

**Comment by Lackeyt** [comment]
Thank you I think I should be set now

**Comment by Nyctara** [comment]
Glad to help :)
