### ISSUE TITLE
HELP! Can't get my bot online!

### ISSUE THREAD

**Issue by liverbrain** [renesansz/discord-greeter-bot#120]
I've tried just about everything. The bot is on my server, but it's offline. Is it a code error??

**Comment by sarthaktexas** [comment]
Show me ur code

**Comment by axelgreavette** [comment]
If there's no errors then open your directory in command prompt or Git Bash and execute the following command:

`npm install https://github.com/woor/discord.io/tarball/gateway_v6`

**Comment by alucidwolf** [comment]
Thanks for the solution, Is it possible to add it to the tutorial post?

**Comment by axelgreavette** [comment]
I added it to this Repo, however, as the Medium tutorial is @renesansz's only he can update that.

**Comment by renesansz** [comment]
thanks @axelgreavette I'll update my post and add your solution.

**Comment by generic-github-user** [comment]
@axelgreavette Thank you so much, this worked perfectly!
