### ISSUE TITLE
.js does not work and cmd gave me 2 warns

### ISSUE THREAD

**Issue by LAMGE2** [renesansz/discord-greeter-bot#13]
I opened up CMD, then go to my folder (C:\Users\lenovo\Desktop\PetaBot) by typing cd C:\Users\lenovo\Desktop\PetaBot and it navigated. Then I used the npm install discord.io winston --save command. And these came up:
![image](https://user-images.githubusercontent.com/17748621/32415467-54c6db30-c24b-11e7-81c1-5e25e77fd36f.png)

Also when I opened my .js file, this error code came.
![image](https://user-images.githubusercontent.com/17748621/32415485-71278a86-c24b-11e7-8584-effa95c6d43e.png)

What should I do?

**Comment by HipHapLion** [comment]
Hi, you will need to open it using a text editor like VS Code or Atom or notepad. To run the app you will need to open cmd in PetaBot directory and run `node bot.js` command. Hope this helps. Please remember to close the issue if the problem is solved. 

Cheers.

**Comment by sheawn** [comment]
Hi @HipHapLion , I am also having the same issue. Could you please restate how to fix the issue? I didn't fully understand it.

**Comment by SlothyDemon** [comment]
I've navigated my way to the folder I have node installed to, I've navigated to the folder where the bot is and ran bot.js from cmd line.. but then I get an error and I was wondering if anyone could be of any help as to the solution. Aside from this error, I've tried following everything to the 't', so any help would be great.
image

**Comment by Nyctara** [comment]
Ok. Firstly the warns are fine because at the bottom it says “updated 2 packages in 1.342s”. Secondly, to run it you could simply type node then drag the file into the CMD Prompt

**Comment by HipHapLion** [comment]
@sheawn Sorry for the late response. If you are still facing the problem can you explain what actions lead to this error?. If you are trying to open the file by double clicking on it then it wouldn't work as the file can only be executed by a JavaScript Engine like NodeJS or a web browser.

**Comment by LAMGE2** [comment]
Okay thanks I now fixed it.
