### ISSUE TITLE
node bot.js doesn't work

### ISSUE THREAD

**Issue by NinBoyX99** [renesansz/discord-greeter-bot#130]
So, I went ahead and read every issue, and I keep using node bot.js but everytime I get this response.
![image](https://user-images.githubusercontent.com/41029569/42483468-370387c2-83b3-11e8-805a-9acf32c59505.png)

**Comment by xandermathews** [comment]
just remove the comma and pair of parens.
The line from the sample code is:
```
logger.remove(logger.transports.Console);
```

**Comment by NinBoyX99** [comment]
@xandermathews So, I tried that. Here's the result. Any clue on what next? Thanks for your help. 
![capture](https://user-images.githubusercontent.com/41029569/42740512-44450d6a-886e-11e8-8a05-0f49b8e2c3bc.PNG)

**Comment by xandermathews** [comment]
you have to write the auth.json by hand, as its only contents are your own bot's secret auth key.

First, make sure you have "manage server" permissions on the discord server you're plugging your bot into.

Then follow https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token

then return to the auth.json part of https://medium.com/davao-js/tutorial-creating-a-simple-discord-bot-9465a2764dc0

I just did this for the first time in the last few hours, and got my bot reading and responding working with the above.  (I also hacked out winston, as it didn't work out of the box and I'm just using console out.)

**Comment by NinBoyX99** [comment]
@xandermathews Thanks, I think I've managed to get through that part now. However, it comes up with no definition for winston. May I ask how you hacked him out?

**Comment by xandermathews** [comment]
@NinBoyX99 
sure -- everywhere the bot tries to log using winston "logger.info" replace with "console.log".

then you can delete the winston config (add/remove/level) and stop require()ing it.

**Comment by superlegend1** [comment]
I am having troubles wit node bot.js too.
I realized that I posted the wrong token in auth.json, but even after fixing that, I still encounter the same problem. I tried reinstalling Discord.io and winston, but it has no effect. I checked all the codes and everything is ok. Any suggestions/
