### ISSUE TITLE
Nothing happens after showing "messages"

### ISSUE THREAD

**Issue by UnnamedDeo** [renesansz/discord-greeter-bot#132]
![screenshot 88](https://user-images.githubusercontent.com/41131043/42603911-7b882dda-85a2-11e8-9da5-f5dd8df4d0f4.png)
Cannot type in the cmd after this either

**Comment by sarthaktexas** [comment]
this is supposed to happen...

**Comment by dpadilla1** [comment]
This is where I am stuck as well. Anybody have a solution?
