### ISSUE TITLE
installing npm install woor/discord.io#gateway_v6 --save and found the error

### ISSUE THREAD

**Issue by Niellol** [renesansz/discord-greeter-bot#135]
![image](https://user-images.githubusercontent.com/28217901/42693038-ef38f044-86d7-11e8-9b58-11dbcca04b9d.png)

**Comment by Niellol** [comment]
I have install git but does the directory affects it?

**Comment by Niellol** [comment]
![image](https://user-images.githubusercontent.com/28217901/42696258-e0978a96-86e1-11e8-99a4-81cbec53abbd.png)

**Comment by xandermathews** [comment]
@Niellol your second screenshot makes it look like you've successfully installed git and put it in your $PATH (or %PATH% if that's still what window's calls it.)

Your new error looks more like your https request is being stopped before getting to github.com. (The only example I can think of that's not a messed up network config or attack is getting on some coffeeshop wifis requires you to click yes, and they're willing to redirect all HTTP(s) to themselves til you do.)

Can you reach https://github.com in a browser?
If so, perhaps you should try using the package.json that this repo uses, which is slightly different from the blog instructions you're following:

don't know if this actually works -- it could go to the same place, but I've not tested this npm syntax on this package:
```
npm install https://github.com/woor/discord.io/tarball/gateway_v6

```

But this _does_ work as of today:
```
npm install github:woor/discord.io#gateway_v6
```

BEFORE you install the above, I recommend you delete node_modules and remove all references to discord.io from package.json dependencies. The below is exactly what your dependencies section should be after running the above:
```
    "dependencies": {
        "discord.io": "github:woor/discord.io#gateway_v6",
        "winston": "^3.0.0"
    }
```

**Comment by Niellol** [comment]
![img20180716173042](https://user-images.githubusercontent.com/28217901/42754398-8d5ac98a-891e-11e8-9d95-81d5eefdda24.jpg)
![img20180716173424](https://user-images.githubusercontent.com/28217901/42754407-979455d8-891e-11e8-84ae-bc8c38a7f5b7.jpg)
Using the new syntax I got another bug though I can still download it by copy and paste it in the browser as you can see

**Comment by xandermathews** [comment]
@Niellol 
Yes, it's because you're putting your project under program files. Program Files\Git should _only_ be for the git binary, not anything else like git config or project files.

That windows directory has extra security that blocks apps from writing to it, and NPM is just another app.

Projects like this work better under something like c:\code\mydiscordbot
