### ISSUE TITLE
How to test if user has a role?

### ISSUE THREAD

**Issue by bob1171** [renesansz/discord-greeter-bot#14]
^

**Comment by HipHapLion** [comment]
There is information regarding roles [here](https://izy521.gitbooks.io/discord-io/content/Resources/Role.html). For information regarding the API please refer to the [offical docs](https://izy521.gitbooks.io/discord-io/) and the [repo](https://github.com/izy521/discord.io). If you are having problems with the api or need help, opening an issue on the official repo is the best option. Hope this answers your question.

Cheers.
