### ISSUE TITLE
HELP!  Error with running bot in command prompt?

### ISSUE THREAD

**Issue by Mineash** [renesansz/discord-greeter-bot#142]
![image](https://user-images.githubusercontent.com/41843834/43361699-8ceb00be-929c-11e8-8c9f-eda072e50033.png)
This happens to me when i run the files in the Node.JS cmd. Everything is copypasted from the website except for a few new commands i inserted.

Here's the code:

var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
       
        args = args.splice(1);
        switch(cmd) {
            case 'ping':
                bot.sendMessage({
                    to: channelID,
                    message: 'Pong!'
                });
		    case 'LOLbot':
			    bot.sendMessage({
					to: channelID,
					message: 'You called?'
                }); 
				case 'LOLbot':
			    bot.sendMessage({
					to: channelID,
					message: 'You called?'
                }); 
				 break;
            // Just add any case commands if you want to..
         }
     }
});

**Comment by FunkyNeonChickN** [comment]
I have this too! Somebody help!!!

**Comment by FunkyNeonChickN** [comment]
https://github.com/renesansz/discord-greeter-bot/issues/137 this is the answer @Mineash
