### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by lleblansch** [renesansz/discord-greeter-bot#144]
![gfhsdfghsgf](https://user-images.githubusercontent.com/32883851/43401495-99a36fce-9410-11e8-89f1-a79bf4df7450.png)

I keep getting this error and I don't know what's causing it.

**Comment by sarthaktexas** [comment]
Show me your code. Make sure to take the token out of the code but replace it with some random text.

**Comment by lleblansch** [comment]
I started another discord bot using discord.js and I don’t have any issues, but since I wanted a working bot I put the token in the bot.js for ease of access and I didn’t have any issues.

I used this to authorize the bot:
`
// At the beginning of bot.js
const discordToken = ‘your token here’

// At the end of bot.js
bot.login(discordToken);
`

I hope this helps some people.

**Comment by lleblansch** [comment]
``
