### ISSUE TITLE
Trying to "npm install woor/discord.io#gateway_v6 --save" but there are errors

### ISSUE THREAD

**Issue by Henati** [renesansz/discord-greeter-bot#147]
![aaacvdad](https://user-images.githubusercontent.com/42076768/43663993-945e203c-976b-11e8-8263-c89f58d6d558.PNG)

I have no idea how to do it, I barerly know JS and was working on it for quite a while and still don't get it. Need help T^T

**Comment by CrazyProGamer24** [comment]
i don't know much either but from my five days worth of googling and trial and error i know that every letter and space must be exactly the same as the original so maybe try looking for writing mistakes

**Comment by TheMightyAnt117** [comment]
i had the same issue and did some heavy research on the ENOGIT error code. Looks like you need GIT installed on your computer. (that was my issue) This is the troubleshooting page that i found out about the ENOGIT error https://github.com/npm/npm/wiki/Troubleshooting And this is where it lead me to https://git-scm.com/book/en/v2/Getting-Started-Installing-Git After installing GIT it was able to run the code without any errors.
