### ISSUE TITLE
Bot is online, but not working

### ISSUE THREAD

**Issue by superlegend1** [renesansz/discord-greeter-bot#148]
I managed to get my bot online, but when I post commands, I get no reply.
Here is the code:

var Discord = require('discord.io');

var logger = require('winston');
var auth = require('./auth.json');

// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';

// Initialize Discord Bot
var bot = new Discord.Client({
    token: auth.token,
    autorun: true
});

bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});

bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it needs to execute a command
    // for this script it will listen for messages that will start with `!`
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];

        args = args.splice(1);

        switch(cmd) {
            // !ping
            case 'ping':
                bot.sendMessage({ to: channelID, message: 'Pong!' });
            break;
            default:
                bot.sendMessage({ to: channelID, message: 'Unknown command.' });
        }
    }
})

if (message.substring(0, 1) == ‘!’) {
var args = message.substring(1).split(‘ ‘);
var cmd = args[0];
args = args.splice(1);
switch(cmd) {
case ‘intro’:
bot.sendMessage({
to: channelID,
message: ‘Greetings! Welcome to the server!’
});
break;
}
}
});

What do you guys think?

**Comment by superlegend1** [comment]
I tried giving it a role with administration rights and stuff, but it has no effect

**Comment by sarthaktexas** [comment]
Ok, I really want to call you stupid, but I understand you're a beginner. Use this code: https://hastebin.com/sefodaziqe.js

**Comment by superlegend1** [comment]
My apologies, but when I click on that link, all I find is an empty page...

**Comment by superlegend1** [comment]
I finally got the link to work xD
I noted the areas of change. Thanks for helping me out! :-)
