### ISSUE TITLE
Running the node bot.js

### ISSUE THREAD

**Issue by SlothyDemon** [renesansz/discord-greeter-bot#15]
I've navigated my way to the folder I have node installed to, I've navigated to the folder where the bot is and ran bot.js from cmd line.. but then I get an error and I was wondering if anyone could be of any help as to the solution. Aside from this error, I've tried following everything to the 't', so any help would be great.
![image](https://user-images.githubusercontent.com/33442048/32476895-b653b2f0-c337-11e7-905f-e32b2bf22fb4.png)

**Comment by HipHapLion** [comment]
Could you please provide more information such as, what is Windows using to open the file? Could you provide the steps to recreate the error?. The error is similar to issue #13, please check the comments in the older issue and see if solves the problem. Unless the problem your facing is much different from the older issue please close this issue and post a comment on the previous issue.

Cheers.
