### ISSUE TITLE
WARN saveError ENOENT

### ISSUE THREAD

**Issue by JolieMariella** [renesansz/discord-greeter-bot#152]
So I'll be honest, I'm a complete noob to coding, please be gentle, lol. I just really wanted to make a custom bot for my discord server and it seems to have blown up in my face. Like many others, I went through that Davao JS walkthrough to make my bot, double and triple checked everything, but this is all Command Prompt is giving me. A quick google suggested running as admin, so I tried that too and no difference.
![croppercapture 979](https://user-images.githubusercontent.com/42439178/44206700-1c832580-a107-11e8-98b6-4b6207e91ded.png)

**Comment by JaydenhumphreyYT** [comment]
I am getting the same error
