### ISSUE TITLE
node bot.js Just Makes a New Line

### ISSUE THREAD

**Issue by tmcdonagh** [renesansz/discord-greeter-bot#158]
I copy and pasted the bot.js added my token to the auth.json and have the package.json basically the same but it just makes a [new line](https://imgur.com/a/OPigsuj) and I can't understand what's wrong. I've tried [this one](https://github.com/renesansz/discord-greeter-bot/issues/105) and [this one](https://github.com/renesansz/discord-greeter-bot/issues/48) and neither of the solutions seem to work. Any help is appreciated.

**Comment by tmcdonagh** [comment]
I ended up using different example code

**Comment by stevenjguan** [comment]
Hey, @tmcdonagh which example code did you end up using? I am having the same issue and would like to start with an example that people have had recent success with!

Thanks in advance.
