### ISSUE TITLE
Adding more commands

### ISSUE THREAD

**Issue by BTDaniel** [renesansz/discord-greeter-bot#17]
How can i add more commands? Like for music or like !ping

**Comment by sheawn** [comment]
I too would also like to know how to add more commands. However, I do not believe that you could possibly also add a music feature to the bot.

**Comment by sheawn** [comment]
@BTDaniel I was tinkering with the code and found out the solution. Simply copy this code below the `break;` of the first command.

`			// !ping
            case 'ping':
                bot.sendMessage({
                    to: channelID,
                    message: 'Pong!'
                });
            break;`
Repeat it every time you want to add a command. It works for me, but I cannot guarantee it will work for you.

**Comment by BTDaniel** [comment]
Great, thank you!

**Comment by sheawn** [comment]
No Problem! I'm glad I was able to help :D

**Comment by Etanarvazac** [comment]
@BTDaniel Erm... Ticket isn't closed.

**Comment by axelgreavette** [comment]
or change you code to if/else statements. way easier. just go 
```
if(command == 'lenny') {
bot.sendMessage ({
to:channelID,
message: '( ͡° ͜ʖ ͡°)'
});
};
```
