### ISSUE TITLE
not sure what ive done wrong

### ISSUE THREAD

**Issue by prysta** [renesansz/discord-greeter-bot#171]
C:\code>cd\

C:\>cd code\bot

C:\code\bot>npm install discord.io winston --save
npm ERR! file C:\code\bot\package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected token � in JSON at position 3 while parsing near '{
npm ERR! �name�: �greeter-bot...'
npm ERR! File: C:\code\bot\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pryst\AppData\Roaming\npm-cache\_logs\2018-09-09T00_06_32_263Z-debug.log

C:\code\bot>

**Comment by KaushalGangwar** [comment]
@prysta  Seems like there is an issue with  package.json.

**Comment by SLia0** [comment]
If you copy pasted from a tutorial, delete the quotation marks and retype them. Some tutorials use symbols and not the actual readable text.

**Comment by ClapperYT** [comment]
you need to install outside of your bots file

code should be 

> npm install discord.io Winston --save
> "cmd says something like installed"

>cd C:\ (your file location)
C:/location> node bot.js
