### ISSUE TITLE
My auth.json is the only file in my discordbot, that is not a json file.

### ISSUE THREAD

**Issue by GrantedLegacy** [renesansz/discord-greeter-bot#178]
Cannot find module './auth.json'
It is the only "file" type in my discord bot. 
Also, my bot.js file turned into a "Bot" file. 
Whenever I try to open the bot file, it shows this
Windows Script Host
❌ Script C:/Users\Daniel\Documents\DiscordBot\bot.js
Line: 1
Char: 1
Error: Object expected
Code: 800-13--
Source: Microsoft Jscript runtime error

What happened here?

**Comment by HypeRayy** [comment]
You need to open it in Node.js

Start by opening Node.js command prompt and type "cd C:/Users\Daniel\Documents\DiscordBot\bot.js"

Then type "node bot".

(both without quotation marks)
