### ISSUE TITLE
node bot.js error 

### ISSUE THREAD

**Issue by MrN00BZ** [renesansz/discord-greeter-bot#183]
![screenshot_2](https://user-images.githubusercontent.com/44274500/47178315-2dc0fc00-d31b-11e8-8e8a-7dace1d97eb9.png)
Please help this is very annoying

**Comment by huxxcb** [comment]
i am also getting this error, perhaps the winston library updated and is not backwards compatible?

**Comment by huxxcb** [comment]
@MrN00BZ i found the solution to the issue, in another issue.
> Change the code:
> from
> logger.add(logger.transports.Console
> logger.add(**new** logger.transports.Console
> 
> it should work now

**Comment by BananaClipStudio** [comment]
Alright, I no longer get the error but the bot is still offline on the channel.
