### ISSUE TITLE
node bot.js

### ISSUE THREAD

**Issue by nekonugget86** [renesansz/discord-greeter-bot#184]
I've followed all steps exactly as explained but when I run node bot.js this is the error message I get. Help![]
![error](https://user-images.githubusercontent.com/44419086/47398561-2b371b80-d6fa-11e8-8706-e8e1dfeac093.PNG)

**Comment by Regularguy36** [comment]
Is auth.json in the same location as bot.js? if not, you'll need to move them to the same location.

**Comment by nekonugget86** [comment]
They are in the same folder
