### ISSUE TITLE
 Error: Invalid transport, must be an object with a log method.

### ISSUE THREAD

**Issue by Nameless9** [renesansz/discord-greeter-bot#186]
I've installed winston 1.3.1 and it seems it was supported for 1.2.x and not 1.3.x. (from online) There were many subsections of winstons like winston-loggly etc and it would be helpful if someone who did this tutorial can help me out

**Comment by Nameless9** [comment]
maninuni commented 15 days ago 

Change the code: 
from logger.add(logger.transports.Console 
to logger.add(new logger.transports.Console
 it should work now

Found a solution. thanks

**Comment by BananaClipStudio** [comment]
What was your solution? I tried changing the code in the above comment and I got no errors this time but the bot didn't go online

**Comment by Nameless9** [comment]
Sorry for the delay. That worked out for me. I didn't downgrade to 1.2.x, I left it as 1.3.1 and used "new" keyword. I have stopped using this way to develop the bot however.

Although, this example helped me get started but I moved on to using discord.js. Discord.js is very orderly, logical and simple and I was able to make a simple project using it
