### ISSUE TITLE
JSON Problems

### ISSUE THREAD

**Issue by hyprrxurr** [renesansz/discord-greeter-bot#187]
Dont know how to fix this? 

![image](https://user-images.githubusercontent.com/44785029/48020731-83c0dc80-e12e-11e8-8d32-f5fbd1c57a7d.png)
 
i dont know what to do pls help

**Comment by vitorsly** [comment]
I think I might know the issue, you might be using “” instead of "" around everything in the package file. Try and change them and see if it works, it worked for me.

**Comment by appuchias** [comment]
That was the answer
