### ISSUE TITLE
I added more commands and this happened, please help!!1

### ISSUE THREAD

**Issue by LAMGE2** [renesansz/discord-greeter-bot#19]
![boterrorpetabotv1](https://user-images.githubusercontent.com/17748621/32960822-6fe637c2-cbd7-11e7-8653-92cfc1a20f4f.JPG)

**I JUST ADDED MORE COMMANDS AND THIS ERROR HAPPENED.**

And that was my code (bot.js):

`var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
       
        args = args.splice(1);
        switch(cmd) {
            // !ping
            case 'ping':
                bot.sendMessage({
                    to: channelID,
                    message: 'Pong!'
                });
            break;
            // Just add any case commands if you want to..

 args = args.splice(1);
        switch(cmd) {
            // !ping
            case 'Selamunaleykum!':
                bot.sendMessage({
                    to: channelID,
                    message: 'Aleykum Selam!'
                });

 args = args.splice(1);
        switch(cmd) {
            // !ping
            case 'invite':
                bot.sendMessage({
                    to: channelID,
                    message: 'Henuz davet etme linki sadece testerlara ozel. Tesekkurler.'
                });

 args = args.splice(1);
        switch(cmd) {
            // !ping
            case 'help':
                bot.sendMessage({
                    to: channelID,
                    message: 'Kullanılabilecegin komutlar: !invite, !help, !Selamunaleykum!, !ping'
                });
         }
     }
});`

**Comment by LAMGE2** [comment]
The code looks like not fully highlighted gray so this is the code:

var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
       
        args = args.splice(1);
        switch(cmd) {
            // !ping
            case 'ping':
                bot.sendMessage({
                    to: channelID,
                    message: 'Pong!'
                });
            break;
            // Just add any case commands if you want to..

 args = args.splice(1);
        switch(cmd) {
            // !ping
            case 'Selamunaleykum!':
                bot.sendMessage({
                    to: channelID,
                    message: 'Aleykum Selam!'
                });

 args = args.splice(1);
        switch(cmd) {
            // !ping
            case 'invite':
                bot.sendMessage({
                    to: channelID,
                    message: 'Henuz davet etme linki sadece testerlara ozel. Tesekkurler.'
                });

 args = args.splice(1);
        switch(cmd) {
            // !ping
            case 'help':
                bot.sendMessage({
                    to: channelID,
                    message: 'Kullanılabilecegin komutlar: !invite, !help, !Selamunaleykum!, !ping'
                });
         }
     }
});

**Comment by HipHapLion** [comment]
Remove the ')' from line 66. Also you can format the code using markdown, check this [guide](guides.github.com/features/mastering-markdown/#syntax) to find out how.
```JavaScript
message: 'Kullanılabilecegin komutlar: !invite, !help, !Selamunaleykum!, !ping'
});
}
}
});  // <-- this line
```

**Comment by Nyctara** [comment]
remove the args = args.splice(1);
switch(cmd) { from all the commands except for the first one... you should have a basic understanding of js before trying to make a a bot, just saying.
