### ISSUE TITLE
Error when running node bot.js

### ISSUE THREAD

**Issue by Razor1928** [renesansz/discord-greeter-bot#192]
Here is a screenshot of my problem, if anyone could help it would be very appreciated, i can also provide screenshots of my files if needed.
![image](https://user-images.githubusercontent.com/45667353/49599712-93c01c00-f979-11e8-89ba-1d5506db1f3f.png)

**Comment by EGobi** [comment]
Yeah, same.

**Comment by EGobi** [comment]
Workaround (kinda) I've found:
Comment lines 5 to 9 and 15 to 19, i.e.:

```
/*logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';*/
```
and
```
/*bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});*/
```

**Comment by Bellesboy** [comment]
> Workaround (kinda) I've found:
> Comment lines 5 to 9 and 15 to 19, i.e.:
> 
> ```
> /*logger.remove(logger.transports.Console);
> logger.add(logger.transports.Console, {
>     colorize: true
> });
> logger.level = 'debug';*/
> ```
> and
> 
> ```
> /*bot.on('ready', function (evt) {
>     logger.info('Connected');
>     logger.info('Logged in as: ');
>     logger.info(bot.username + ' - (' + bot.id + ')');
> });*/
> ```

I've tried this an when I do I don't get any message back and the bot stays offline, any other ideas?

**Comment by Jwtotter** [comment]
fixed this by uninstalling winston and reinstalling and older version (v2.4.4). apparently v3 onwards isn't compatible

**Comment by miststlkr** [comment]
to make it work with winston3, just change the logger.add line to this:

logger.add(new logger.transports.Console(), {


I still haven't gotten the bot online, but that gets rid of the error

**Comment by ocolina6720** [comment]
Same problem here.
Any progress?
