### ISSUE TITLE
Node bot.js

### ISSUE THREAD

**Issue by CASMSpaido** [renesansz/discord-greeter-bot#193]
![image](https://user-images.githubusercontent.com/45903820/50046919-61ee3a00-008a-11e9-9f01-f7e85a6a67f5.png)

**Comment by TheBorinator** [comment]
I find the same problem

**Comment by jenaus** [comment]
so do i

**Comment by jdavies** [comment]
Check to ensure your JSON is properly formatted. The fact you are getting a syntax error means that it is not properly formatted. A good resource for verifying your JSON is http://json.parser.online.fr/
From the looks of the error from the OP si would say the token is not in quotes. Here is an example of a working auth.json file (the token has been redacted, of course):
{
"token:": "NSSSSDHDS&DSDFFFHFHFHFHHDHDH8787827627ASHD858686QZC"
}
