### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by OctoTot** [renesansz/discord-greeter-bot#195]
I have no idea how to fix this error. I could use some help. Its probably something simple but i'm fairly new to this kind of thing.
![error](https://user-images.githubusercontent.com/46140595/50438914-e324a880-08a4-11e9-8bf6-ad987be929fe.png)
![code](https://user-images.githubusercontent.com/46140595/50439395-c7220680-08a6-11e9-8b36-2010591c047a.png)

**Comment by MyUsernamesThis** [comment]
i have the same error it have no idea what it means i guess im gonna be unlucky and not be able to make a discord bot :(
