### ISSUE TITLE
More commands

### ISSUE THREAD

**Issue by blockyTj995** [renesansz/discord-greeter-bot#198]
Im not good at js or nodejs. and i want to know how to put in more commands in the bot. heres my code ,

var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(new logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (message.substring(0, 1) == '~') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
       
        args = args.splice(1);
        switch(cmd) {
            // ~yeet
            case 'Ping':
                bot.sendMessage({
                    to: channelID,
                    message: Pong'
                });
            break;            break;
         }
     }
});

**Comment by nooknpj** [comment]
I too am still learning about javascript and working on discord bots so there might be some mistakes but I think it still could help you.

To add more commands, add more switch cases.
In your code the bot takes input in and split the input string with a blank space (" ") and keeps the results in an array called args. (without your command prefix; in your case it's the '~' )
and the var cmd = args[0] is the first element of that array which are usually the command name.
so in the switch case 'ping' will run if the first element of args is 'ping'
if you want to add more command you can make a switch case 'newCommandName'
and set the string output in the message property inside bot.sendMessage({

The following code is the one I tried. Note that I use '!' as the command prefix and I didn't use args.splice(1); so the array args may look different so you should try to console.log(args) to see your array.

```
bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
        console.log(args);

        //args = args.splice(1);

        switch (cmd) {

            // case !Ping
            case 'ping':
                //console.log("Ping requested");
                bot.sendMessage({
                    to: channelID,
                    message: 'Pong!'
                });
                break;

            // normal command with no input parameter
            // case !coinFlip
            case 'coinFlip':
                let result;
                if (Math.random() > 0.5) {
                    result = "Head";
                } else {
                    result = "Tail";
                }

                bot.sendMessage({
                    to: channelID,
                    message: result
                });
                break;

            // normal command with 1 input parameter
            // case Random(int i)
            // returns random number range from [0,i] (i is included)
            case 'random':
                console.log("random");

                // check if the input is length 2 ['random' , int ] and the args[1] is Number
                if (args.length != 2 || isNaN(args[1])) {
                    bot.sendMessage({
                        to: channelID,
                        message: "Invalid Arguments: random (int)"
                    });

                } else {
                    let num = parseInt(args[1]) + 1;
                    // let num = parseInt(args[1]) if you want the random range to be [0,i-1] (i is not included)

                    let result = (Math.floor(Math.random() * num)).toString();
                    console.log(result);
                    bot.sendMessage({
                        to: channelID,
                        message: result
                    });
                }
                break;


        }
    }
});
```

**Comment by pongored81** [comment]
You would just need to add another switch statement if you wanted to make simple commands where the bot responded.
`
 switch(cmd) {
        case 'Ping':
            bot.sendMessage({
                to: channelID,
                message: Pong'
            });
        break;          
        case 'Hello':
            bot.sendMessage({
                to: channelID,
                message: 'Goodbye'
  break;
     });
`

**Comment by deadpoolex** [comment]
@pongored81 I tried this and it gives me and error about the break
