### ISSUE TITLE
PLZ help

### ISSUE THREAD

**Issue by LuZrOg0** [renesansz/discord-greeter-bot#203]
![bug](https://user-images.githubusercontent.com/44816256/52164142-04bb5000-26ed-11e9-85fc-0acf63c65679.PNG)

When i do the, npm install https://github.com/woor/discord.io/tarball/gateway_v6 and the other nothing past and when i do node bot.js, look the image.

**Comment by NickXavier** [comment]
Did you run cmd as an Administrator? That fixed it for me.

**Comment by NickXavier** [comment]
Check where your trying to use those npm commands.
They should be used in your bot folder.

**Comment by NickXavier** [comment]
Check where your trying to use those npm commands are used to the location of your bot folder.

**Comment by mero789** [comment]
Make sure u have installed both npm packages  npm install discord.io winston --save and npm install https://github.com/woor/discord.io/tarball/gateway_v6)
