### ISSUE TITLE
My issuse

### ISSUE THREAD

**Issue by SnitchsYa** [renesansz/discord-greeter-bot#205]
http://prntscr.com/mk2n91

Getting 2 warns and will not come online

this is the folder that the shits in
http://prntscr.com/mk2nk7

**Comment by SnitchsYa** [comment]
http://prntscr.com/mk32su

**Comment by fupuchu** [comment]
that's due to a version issue on wintson,

simply change your winston version to

`"winston":` "2*.3.1"`

**Comment by NickXavier** [comment]
Works fine for me. Did you check your winston version in package.json? It should be like this.
    "winston": "^3.2.1"
