### ISSUE TITLE
node bot.js issue 

### ISSUE THREAD

**Issue by jaimil1234** [renesansz/discord-greeter-bot#207]
i have this error pls tell me fix 
![problem](https://user-images.githubusercontent.com/47783882/53022067-72eb6b00-3480-11e9-8708-1ea648a36a1a.PNG)

**Comment by NickXavier** [comment]
Did you check your auth.json and package.json has actually used these symbols ""  In code, these symbols are quite different. Give it a look, check it and then save them. It should work fine.
