### ISSUE TITLE
Bot offline 

### ISSUE THREAD

**Issue by MrJMAL** [renesansz/discord-greeter-bot#215]
![image](https://user-images.githubusercontent.com/48929821/54955142-ca339e00-4f4c-11e9-850c-f09fd4ffbed1.png)
![image](https://user-images.githubusercontent.com/48929821/54955164-d28bd900-4f4c-11e9-9689-f533ffbc6bbb.png)
My bot is all the time offline

**Comment by Winigan** [comment]
An additional NPM library should be installed.
npm install https://github.com/woor/discord.io/tarball/gateway_v6

Check the bottom of this page to have the source.
https://medium.com/davao-js/tutorial-creating-a-simple-discord-bot-9465a2764dc0
