### ISSUE TITLE
How to add more commands?

### ISSUE THREAD

**Issue by A0RV** [renesansz/discord-greeter-bot#22]
I dont know how? 

Here is my code

var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
       
        args = args.splice(1);
        switch(cmd) {
            // !ping
            case 'lenny':
                bot.sendMessage({
                    to: channelID,
                    message: '( ͡° ͜ʖ ͡°)'
                });
            break;
            // Just add any case commands if you want to..
         }
     }
});

**Comment by Nyctara** [comment]
case 'lenny':
            bot.sendMessage({
                to: channelID,
                message: '( ͡° ͜ʖ ͡°)'
            });
        break;
case 'another':
            bot.sendMessage({
                to: channelID,
                message: 'wow another command'
            });
        break;
case 'another':
            bot.sendMessage({
                to: channelID,
                message: 'wow another command'
            });
        break;
case 'another':
            bot.sendMessage({
                to: channelID,
                message: 'wow another command'
            });
        break;
And so on

**Comment by A0RV** [comment]
oh thanks

**Comment by Etanarvazac** [comment]
@A0RV Basic JS knowledge you could have figured that out. Remember to add a break before a new command otherwise the higher one will send lower ones as well.

**Comment by axelgreavette** [comment]
or change you code to if/else statements. way easier. just go 
```
if(command == 'lenny') {
bot.sendMessage ({
to:channelID,
message: '( ͡° ͜ʖ ͡°)'
});
};
```

**Comment by lilcheo** [comment]
How do i add under bot on the side were it shows everyone online By.Name do prefix=!help

**Comment by axelgreavette** [comment]
add this to the `bot.on{etc}` function:

```
bot.setPresence ({
            game:{
                name: p,
                type: '1', // can be '2' for 'listening to' prefix // can be '3' for 'watching' prefix
                url: 'https://www.twitch.tv/axelgreavette'
            }
        });
```

**Comment by radio-bullit** [comment]
how to use command for the bot and how to do a stream in it so that the can see what is playing on my stream watch on https://radio-bullit.nl/luisteren/ then you see what i mean  i wand that on my discord-bot and how can i let the bot say now playing and then the music what now is playing on my stream please help me whit that and how to do new commands
whit ! and then the message like thise one on *:text:!gooit*:#: {
  msg $chan 0,1 $nick gooit naar $2 een $3- like this message how do i do that please help me
