### ISSUE TITLE
Embed Image

### ISSUE THREAD

**Issue by ElcairFarron** [renesansz/discord-greeter-bot#223]
Hi there, renesansz!

Could you tell me the details to add a comannd that would embed an image via url?

Thank you in advance.

**Comment by NightWolf1038** [comment]
Write this inside you "client.on('message'..." code:
```
if(msg.content.startsWith('!image')){
	var image = msg.content.split(' ').splice(1).join(' '); // Your image URL
	var embed = new Discord.RichEmbed()
	.setTitle('Image')
	.setImage(image); // Image must be an url
	msg.channel.send(embed);
}
```

That's just a basic thing, you can change the command if you want and improve it.
