### ISSUE TITLE
[Not Working] npm install discord.io winston --save #103

### ISSUE THREAD

**Issue by Bubble-Tea** [renesansz/discord-greeter-bot#229]
I've been trying to set up this discord bot as a test but for some reason, this command is not working: “npm install discord.io winston –save.” 
every time I do this command it tells me that I need it to be an original or actuall json file not only a java

**Comment by LouisTheLeaf** [comment]
Answered Here: https://github.com/renesansz/discord-greeter-bot/issues/212

**Comment by AtticusBrendan** [comment]
For me, it is still not working after I've changed all the quotations into ". What should I do? Here is my image below : 
<img width="568" alt="Screenshot 2019-08-14 at 8 56 20 PM" src="https://user-images.githubusercontent.com/54107753/63022689-048ae100-bed6-11e9-86a1-b74e6679d304.png">

**Comment by AtticusBrendan** [comment]
I tried to change it, but that still happened to me.

**Comment by AtticusBrendan** [comment]
<img width="544" alt="Screenshot 2019-08-14 at 9 01 39 PM" src="https://user-images.githubusercontent.com/54107753/63023037-c4782e00-bed6-11e9-9bce-47814e9e52e9.png">
Or did I make a mistake there?

**Comment by cloudmtd** [comment]
If you copied and pasted it from the example, the quotations are incorrect in the example. Replace the quotations to " (replace the ones in the example)

**Comment by m0n0l0gu3** [comment]
I'm having the same issue with an ERR! on each line just like the person above. I've replaced all my " with no luck. Any assistance would be appreciated. :3

**Comment by Jotaro-Kujo-and-Star-Platinum** [comment]
What do I do if I'm getting this: 

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/- - Not found
npm ERR! 404
npm ERR! 404  '-@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Chronos\AppData\Roaming\npm-cache\_logs\2019-09-30T04_40_12_971Z-debug.log

**Comment by renesansz** [comment]
@Jotaro-Kujo-and-Star-Platinum 404 means it can't fetch any packages to the npm registry.
Something is blocking your network please check your firewall, proxy, or any network related configuration in your machine.

**Comment by Jotaro-Kujo-and-Star-Platinum** [comment]
> @Jotaro-Kujo-and-Star-Platinum 404 means it can't fetch any packages to the npm registry.
> Something is blocking your network please check your firewall, proxy, or any network related configuration in your machine.

awww, man. the bad thing about that is that there is no firewall, proxy, etc. im so confused

**Comment by renesansz** [comment]
@Jotaro-Kujo-and-Star-Platinum  can you post the full log here?

**Comment by Jotaro-Kujo-and-Star-Platinum** [comment]
where do i find the full log?

**Comment by Jotaro-Kujo-and-Star-Platinum** [comment]
it's working now.

**Comment by renesansz** [comment]
that's good to hear. I'll close the issue now
