### ISSUE TITLE
message.author and similar variables are always undifineed please help !

### ISSUE THREAD

**Issue by RealSharonX** [renesansz/discord-greeter-bot#230]
var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(new logger.transports.Console, { colorize: true });
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt, author) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
       
        args = args.splice(1);
        switch(cmd) {
            case `isZitounGay`:
                bot.sendMessage({
                    to: channelID,
                    message: `hell yeah`
                });
            break;
            case `sayMyName`:
                bot.sendMessage({  
                    to: channelID,  
                    message: `I am sure you are called ${message.author}`
            });   
            break;
         }
     }
});

**Comment by RealSharonX** [comment]
help please

**Comment by renesansz** [comment]
On this line:
```
        case `sayMyName`:
            bot.sendMessage({  
                to: channelID,  
                message: `I am sure you are called ${message.author}`
        });   
        break;
```

replace your message to `I am sure you are called ${author}`
