### ISSUE TITLE
I want my bot to always be online

### ISSUE THREAD

**Issue by Eeliac** [renesansz/discord-greeter-bot#233]
So I'm trying to have my bot always be online, and when I watched the tutorial from Glitch it wasnt any help and was confusing. I just want my bot to stay online via Glitch but the tutorial on there didn't help at all. Any help??

**Comment by Mariogamerexpert** [comment]
Well I am no expert as Jscript as I am entirely new as well. I have no idea how to fix this issue but how long does the bot stay online before going offline?

**Comment by AtticusBrendan** [comment]
Around 10 minutes for me.

**Comment by Bytooo** [comment]
You should try using something like Heroku to host your bot for free and 24/7
