### ISSUE TITLE
Multiple Responses Occur via Single Command

### ISSUE THREAD

**Issue by mrhyderager** [renesansz/discord-greeter-bot#234]
I used the code and got the bot to work with a single case, but it seems like now that I've added additional cases, when sending a command, the response messages for multiple cases return.

For example, see the following cases:

 ```
bot.on('message', function (user, userID, channelID, message, evt) {
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];	
	
        args = args.splice(1);
        switch(cmd) {
            case 'turkey':
                bot.sendMessage({
                    to: channelID,
                    message: ':turkey: gobble gobble cockadoodle doo'
                });		
	    case 'monny':
                bot.sendMessage({
                    to: channelID,
                    message: '@Monathan Jchendrix where you be'
                });	
```

So what happens is when a !turkey command is sent, the bot will send multiple messages:

Botty_Boi_2:
      @Monathan Jchendrix where you be
      :turkey: gobble gobble cockadoodle doo
      
Any idea why a single command is calling multiple cases even when they don't apply?

**Comment by GuNfRe4k** [comment]
You need a break line

like so
bot.on('message', function (user, userID, channelID, message, evt) {
   if (message.substring(0, 1) == '!') {
       var args = message.substring(1).split(' ');
       var cmd = args[0];	
   
       args = args.splice(1);
       switch(cmd) {
           case 'turkey':
               bot.sendMessage({
                   to: channelID,
                   message: ':turkey: gobble gobble cockadoodle doo'
               });		
          break
       case 'monny':
               bot.sendMessage({
                   to: channelID,
                   message: '@Monathan Jchendrix where you be'
               });

**Comment by mrhyderager** [comment]
That took care of it. Thanks!
