### ISSUE TITLE
Unexpected token )

### ISSUE THREAD

**Issue by Mariogamerexpert** [renesansz/discord-greeter-bot#235]
Every time I try to run the bot, I receive an error exclaiming "Unexpected token )"

Solution?

**Comment by HeresHavi** [comment]
Make sure that there is no space between the name in the package.json file at "name":

**Comment by Mariogamerexpert** [comment]
So "name: BotName"?

**Comment by Ultimate73** [comment]
I am also getting this unexpected token, fixed what @HeresHavi stated but did not make it work! Please help

**Comment by renesansz** [comment]
@Ultimate73 can you provide your code and let's see what's the problem there?
