### ISSUE TITLE
Node bot.js 

### ISSUE THREAD

**Issue by Ahmadh26** [renesansz/discord-greeter-bot#244]
here is what im getting when im executing node.js 

![image](https://user-images.githubusercontent.com/57562297/68528572-39ec7280-02fd-11ea-87e5-901174e4e9e9.png)

**Comment by BenHurricane** [comment]
Try retyping all quotation marks. Sometimes quotation marks copy over in the wrong font and wont be read as such within the json

**Comment by Ahmadh26** [comment]
thanks, already fixed it yesterday but forgot to close the issue.

i appreciate your reply tho <3
