### ISSUE TITLE
Node bot.js

### ISSUE THREAD

**Issue by Gamemodeon123** [renesansz/discord-greeter-bot#246]
![problem](https://user-images.githubusercontent.com/57966219/69195028-ac790180-0af8-11ea-8593-dd1ddf5afb6a.PNG)

**Comment by kingfisher5** [comment]
I had a similar issue, have a look at your auth.json file and look for any typos or weird characters. For me it ended up being I had the wrong quote marks.

**Comment by Gamemodeon123** [comment]
i will try that
