### ISSUE TITLE
Module.js fixed, now syntax error occurs!

### ISSUE THREAD

**Issue by XTherealNinjaX** [renesansz/discord-greeter-bot#25]
So i've done all the steps however when I get to the part where I type in

node bot.js it says error occurred (screenshot)

![capture](https://user-images.githubusercontent.com/34042542/33289812-a31577dc-d3b8-11e7-8667-b1659970c120.PNG)

**Comment by Nyctara** [comment]
Please just look at closed issues before posting this. It’s been resolved multiple times. Just type node and drag the bot.js folder into the cmd Prompt.

**Comment by XTherealNinjaX** [comment]
I do that but the bot doesn't come online still.
