### ISSUE TITLE
in the tutorial you never told people to change the dyno type to worker

### ISSUE THREAD

**Issue by mr-winson** [renesansz/discord-greeter-bot#251]
if they dont it might be frustrating because it will return an R10 error every 60 seconds

just using a procfile would fix it

**Comment by renesansz** [comment]
@mr-winson thank you for clarifying this, I'll find some time to make changes including in the article 👍

**Comment by mr-winson** [comment]
Cool!

**Comment by renesansz** [comment]
Submitted commit to fix the issue. 36c729a

Also updated Medium article, thank you for point this issue @mr-winson!
