### ISSUE TITLE
Bot crashing due to missing start script

### ISSUE THREAD

**Issue by modness-C137** [renesansz/discord-greeter-bot#252]
Hello!

First of all: thanks for the awesome tutorial. However, my bot keeps crashing with the following error message:
>2020-04-07T17:42:17.000000+00:00 app[api]: Build succeeded
>2020-04-07T17:42:18.300776+00:00 heroku[web.1]: State changed from crashed to starting
>2020-04-07T17:42:25.565540+00:00 heroku[web.1]: State changed from starting to crashed
>2020-04-07T17:42:25.479117+00:00 app[web.1]: npm ERR! missing script: start

Since I am new to programming I need help solving this. Thanks in advance and best regards!

**Comment by mr-winson** [comment]
add this into your package.json:
`
"scripts": {
    "start": "node bot.js"
},`

if you need more detail then it should look something like this:

`
  "main": "bot.js",
  "scripts": {
    "start": "node bot.js"
  },
  "keywords": [],`
