### ISSUE TITLE
npm install discord.io winston –save not working

### ISSUE THREAD

**Issue by IanDaBest** [renesansz/discord-greeter-bot#257]
Hello. I am trying to make a discord bot but when I do npm install discord.io winston –save it doesn't work. It says:
npm ERR! code EJSONPARSE
npm ERR! file C:\Users\IanDaBest\Discord\DaBestBot\codes\package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token “ in JSON at position 3 while parsing near '{
npm ERR! JSON.parse “name”: “DaBestBot”,...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\IanDaBest\AppData\Roaming\npm-cache\_logs\2020-06-02T08_14_09_511Z-debug.log

I don't know javascript at all and I am just trying to make my own discord bot.

Details:
Following tutorial: https://www.digitaltrends.com/gaming/how-to-make-a-discord-bot/
OS: Windows 10
I am using Windows Powershell If that helps

**Comment by renesansz** [comment]
> Hello. I am trying to make a discord bot but when I do npm install discord.io winston –save it doesn't work. It says:
> npm ERR! code EJSONPARSE
> npm ERR! file C:\Users\IanDaBest\Discord\DaBestBot\codes\package.json
> npm ERR! JSON.parse Failed to parse json
> npm ERR! JSON.parse Unexpected token “ in JSON at position 3 while parsing near '{
> npm ERR! JSON.parse “name”: “DaBestBot”,...'
> npm ERR! JSON.parse Failed to parse package.json data.
> npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\IanDaBest\AppData\Roaming\npm-cache_logs\2020-06-02T08_14_09_511Z-debug.log
> 
> I don't know javascript at all and I am just trying to make my own discord bot.
> 
> Details:
> Following tutorial: https://www.digitaltrends.com/gaming/how-to-make-a-discord-bot/
> OS: Windows 10
> I am using Windows Powershell If that helps

Please post your package.json content here

**Comment by IanDaBest** [comment]
its is as follows:

{
“name”: “DaBestBot”,
“version”: “1.0.0”,
“description”: “This is DaBestBot”,
“main”: “bot.js”,
“author”: “IanDaBest”,
“dependencies”: {}
}

**Comment by renesansz** [comment]
@IanDaBest it seems you are using wrong double quote character, this might have been caused when you copy/paste the code from Medium.

Use this instead, notice the difference with ” and "
```
{
"name": "DaBestBot",
"version": "1.0.0",
"description": "This is DaBestBot",
"main": "bot.js",
"author": "IanDaBest",
"dependencies": {}
}
```

**Comment by IanDaBest** [comment]
it still didn't work. It said

npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "–save": Tags may not have any characters that
encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!
C:\Users\IanDaBest\AppData\Roaming\npm-cache\_logs\2020-06-08T06_54_21_322Z-debug.log

**Comment by renesansz** [comment]
`npm install discord.io winston --save` it should be `--save` not `–save`

this might have been caused when you copy/paste the code from your reference page.

**Comment by IanDaBest** [comment]
this happened. is this good?

npm notice created a lockfile as package-lock.json. You should commit this
file.
npm WARN DaBestBot@1.0.0 No repository field.
npm WARN DaBestBot@1.0.0 No license field.

+ winston@3.2.1
+ discord.io@2.5.3
added 43 packages from 35 contributors and audited 43 packages in 7.516s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by sarthaktexas** [comment]
yes, that is fine.

**Comment by renesansz** [comment]
since this if resolved. will close this ticket now.
