### ISSUE TITLE
Errors when executing node bot.js in cmd and node terminal

### ISSUE THREAD

**Issue by Whimzaspimza** [renesansz/discord-greeter-bot#259]
Node terminal error:      ^^^

Uncaught SyntaxError: Unexpected identifier

CMD error: internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Users\Owner\bot.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:842:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by cometh8888** [comment]
did you do it with the name of your file

**Comment by Whimzaspimza** [comment]
the name of the file is bot.js
