### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Cloudiergorgon7** [renesansz/discord-greeter-bot#263]
SyntaxError: missing ) after argument list
[90m    at wrapSafe (internal/modules/cjs/loader.js:1117:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1165:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1050:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:938:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m

**Comment by sarthaktexas** [comment]
You are missing an ending parenthesis. Can you post your `bot.js` here so we can help you?
