### ISSUE TITLE
I try to run my discord bot (node bot.js) but nothing happens at all.

### ISSUE THREAD

**Issue by Juakerman** [renesansz/discord-greeter-bot#264]
I've been all night trying to find a fix but many of the posts are either old or didn't work for me. I've made sure to copy over the bot token and not the app token, but the same still happens.
![image](https://user-images.githubusercontent.com/67961206/86909974-3e318f80-c119-11ea-9236-2d36c9b8c4a4.png)

I've also installed git but nothing really changed.

**Comment by sarthaktexas** [comment]
can you show us your `bot.js` and the output when you do `node -v`
