### ISSUE TITLE
Syntax Error when running node bot.js

### ISSUE THREAD

**Issue by AfricaByTot0** [renesansz/discord-greeter-bot#266]
The error
![cmd_58RlFjK6V8](https://user-images.githubusercontent.com/68201109/87254670-3a668a00-c4d8-11ea-90c9-a444681861dc.png)
The inside of my  bot.js
![notepad_dRdJRcs3OV](https://user-images.githubusercontent.com/68201109/87254683-566a2b80-c4d8-11ea-9240-248cadf9220b.png)

**Comment by sarthaktexas** [comment]
You have to post auth.json. And please remove your secrets.

**Comment by AfricaByTot0** [comment]
Uhhh why would you need my token or my name?

**Comment by AfricaByTot0** [comment]
I won't remove my username but my token is NzMxNzM0NTg1MDE2MDU3OTA2.XwtYyA.I6ky71WMbRSYzEtQUlnmEooKCCA

**Comment by sarthaktexas** [comment]
ok. the token *is* the secret. Please regenerate a new token and send the old auth.json.

**Comment by AfricaByTot0** [comment]
DISCORD_TOKEN=NzMxNzM0NTg1MDE2MDU3OTA2.XwtYyA.I6ky71WMbRSYzEtQUlnmEooKCCA

**Comment by sarthaktexas** [comment]
uhh your config is wrong. Try this!
```
[
  "username": "usernamehere",
  "token": "token here"
]
```
