### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by GamingNeverEnds** [renesansz/discord-greeter-bot#267]
This happens every time I try to install it. 
![Screenshot (59)](https://user-images.githubusercontent.com/53358207/87690370-fe892a00-c74e-11ea-869b-2141e85648cd.png)

**Comment by sarthaktexas** [comment]
Nothings technically wrong. Just do node bot.js or node app.js depending on the name!

**Comment by sarthaktexas** [comment]
If you want to get rid of the warning, add these to your package.json. 
```
{
 "repository": "enter repo link",
 "license": "MIT"
}
```

**Comment by sarthaktexas** [comment]
@renesansz should I make a pull request to add these to `package.json`?

**Comment by renesansz** [comment]
@sarthaktexas I think it's just a warning because some important identifier in package.json is missing.
sure, your contribution is most welcome

**Comment by renesansz** [comment]
Merged PR #268
Thanks for the contribution @sarthaktexas
