### ISSUE TITLE
Node bot.js is not working

### ISSUE THREAD

**Issue by CrxsTagz** [renesansz/discord-greeter-bot#269]
I get this message

![mielderia](https://user-images.githubusercontent.com/68723063/88359962-87512880-cd42-11ea-9505-f87a175407da.jpg)

and my code is this:

var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
       
        args = args.splice(1);
        switch(cmd) {
            // !hey
            case 'Hey':
                bot.sendMessage({
                    to: channelID,
                    message: 'klk mmgvs, Welcome to International Coro'
                });
            break;
            // Just add any case commands if you want to..
         }
     }
});

same as the website

**Comment by sarthaktexas** [comment]
send `auth,json` WITHOUT token

**Comment by sarthaktexas** [comment]
actually, replace `auth.json` with `.env` and add this to your `bot.js`:
`require('dotenv').config();`
then in `.env`, put this
`DISCORD_TOKEN: blah blah`
 and finally, 
`token: process.env.DISCORD_TOKEN` (instead of auth.token)

**Comment by CrxsTagz** [comment]
let me see if i get it. i replace the auth with .env which is going to be auth.env

i will put that .env in the variable auth which is going to be auth = require('dotenv').config();
 
and then the token would be token: process.env.DISCORD_TOKEN

**Comment by sarthaktexas** [comment]
sorry for the late reply. I mean replace the file `auth.json` with the file `.env`. and just put the `require` statement at the top. don't need to assign to a variable. and the rest is correct.

**Comment by eltrevii** [comment]
(Reply to ur message)

> I get this message
> 
> ![mielderia](https://user-images.githubusercontent.com/68723063/88359962-87512880-cd42-11ea-9505-f87a175407da.jpg)
> 
> and my code is this:
> 
> var Discord = require('discord.io');
> var logger = require('winston');
> var auth = require('./auth.json');
> // Configure logger settings
> logger.remove(logger.transports.Console);
> logger.add(logger.transports.Console, {
> colorize: true
> });
> logger.level = 'debug';
> // Initialize Discord Bot
> var bot = new Discord.Client({
> token: auth.token,
> autorun: true
> });
> bot.on('ready', function (evt) {
> logger.info('Connected');
> logger.info('Logged in as: ');
> logger.info(bot.username + ' - (' + bot.id + ')');
> });
> bot.on('message', function (user, userID, channelID, message, evt) {
> // Our bot needs to know if it will execute a command
> // It will listen for messages that will start with `!`
> if (message.substring(0, 1) == '!') {
> var args = message.substring(1).split(' ');
> var cmd = args[0];
> 
> ```
>     args = args.splice(1);
>     switch(cmd) {
>         // !hey
>         case 'Hey':
>             bot.sendMessage({
>                 to: channelID,
>                 message: 'klk mmgvs, Welcome to International Coro'
>             });
>         break;
>         // Just add any case commands if you want to..
>      }
>  }
> ```
> 
> });
> 
> same as the website
# You need to see dis
![image](https://user-images.githubusercontent.com/59333567/89435091-aa1d0d00-d744-11ea-9548-15df1f716f6f.png)
