### ISSUE TITLE
Pathing Issues

### ISSUE THREAD

**Issue by KxngCreations** [renesansz/discord-greeter-bot#27]
Hey so i followed your tutorial (which was amazing and easy to follow thank you for that" but when i use 
npm install discord.io winston --save 
![screenshot_21](https://user-images.githubusercontent.com/21984382/33400257-39484bb8-d534-11e7-896d-2451748fe401.png)

This happens not sure but it looks like a pathing issue anyone else with this problem?

**Comment by Nyctara** [comment]
The warns are fine because at the bottom it says “updated 2 packages in 27.382s”

**Comment by KxngCreations** [comment]
Ok so I got it working and have been following the steps to host it on Heroku and i get this



Any ideas on what i may have missed?
