### ISSUE TITLE
I have problems with code

### ISSUE THREAD

**Issue by eltrevii** [renesansz/discord-greeter-bot#273]
# I need help
## Someone knows how to fix this?
![image](https://user-images.githubusercontent.com/59333567/89430412-04b36a80-d73f-11ea-8e36-e6cd8f0e386a.png)

**Comment by Aritz331** [comment]
#269

**Comment by eltrevii** [comment]
This was already solved by me, I've seen the 2nd version of the article I used because the first does not work and it's outdated

**Comment by eltrevii** [comment]
And my second issue was used to mention this one
