### ISSUE TITLE
Bot won't go online

### ISSUE THREAD

**Issue by diceEviscerator** [renesansz/discord-greeter-bot#3]
I've followed the tutorial copying and pasting the code and stuff, the bot is set and it's on my server. But wont go online nor do anything, running node bot.js won't do anything, i supposed that's because of no errors?

**Comment by renesansz** [comment]
yes, the bot should be hosted on a server.
Can you please post some additional details in regards with the issue you're having? (eg: screenshots, node version, etc.)

**Comment by diceEviscerator** [comment]
node version is 6.11.4 
followed your tutorial step by step, just changed the message and the command, and yet just a single one.

how do I host the bot on the server? your tutorial dont say this, it says that once I run 'node bot.js' it will work

**Comment by sayezz** [comment]
bump! have the same issue

**Comment by renesansz** [comment]
@diceEviscerator @sayezz you need a dedicated server to host your bot (eg: Heroku).
I apologize I didn't intend to teach on how to host it on a server, however I can make a follow-up tutorial on how to host the bot to a server.

**Comment by bob1171** [comment]
yes please
