### ISSUE TITLE
Commands with and without

### ISSUE THREAD

**Issue by Shinigami15** [renesansz/discord-greeter-bot#32]
Hey, 

How do I make it so that if someone says something like
"I am going offline"
that the bot then says
"No! You are staying!"
with as trigger "going offline"
while I can still use !commands
like !ping for example.
Thanks in advance.

**Comment by JackTheodoreRipper** [comment]
`bot.on('message', (message) => {
    
    if(message.content == 'I am going offline') {
        message.reply('No! You are staying!');
    }
});`
Is that what you ment....
