### ISSUE TITLE
Bot gets the boot

### ISSUE THREAD

**Issue by SamHayzen** [renesansz/discord-greeter-bot#34]
Every time I run the bot, it immediately gets disconnected.
It doesn't even connect first, it just flat out goes to the disconnect function

To make sure it wasn't my mistake, I created a new project file, and went through the tutorial again. **Twice**

All the files are exactly how they are from the tutorial, and I even tried tokens from multiple bots.
I even gave the project file to a friend on his computer, and it did the exact same thing.

Thank you for your time.

**Comment by einmensch** [comment]
I have the same problem, are you using fedora too?

**Comment by MadMikeyB** [comment]
Looks like the V5 gateway which the `discord.io` npm package was using is deprecated now.

I got the bot working with `npm install woor/discord.io#gateway_v6 --save`

Then I ran `node bot.js` and everything works.
