### ISSUE TITLE
help

### ISSUE THREAD

**Issue by revsonel** [renesansz/discord-greeter-bot#36]
bot.deleteMessages({
						channelID: channelID,
						messageIDs: 
					}, function(err) {
						console.log(err)
					}
what i have to type in messageIDs?

**Comment by revsonel** [comment]
bot.deleteMessages({
						channelID: channelID,
						messageIDs: 
					}, function(err) {
						console.log(err)
					}

**Comment by sarthaktexas** [comment]
in message id you would put the message id of the message you want to delete
