### ISSUE TITLE
Unexpected Token Error?

### ISSUE THREAD

**Issue by H0rologium** [renesansz/discord-greeter-bot#37]
So I recently got an error whenever I try and launch the bot.json from the command line: 
![capture](https://user-images.githubusercontent.com/33498180/34135873-cffc1f3c-e428-11e7-965e-c70b677d2ac2.PNG)

It seems to do this no matter what character is at the first line of the program. But the code is exactly as it is from the tutorial (pics will be put at the end). I've updated everything and im not running the node 9.5 so im not sure what the problem is. The code looks fine...

![bot](https://user-images.githubusercontent.com/33498180/34135962-3699ce92-e429-11e7-93a5-be2b3822bd43.PNG)

**Comment by aerisDoesCodes** [comment]
If I am not mistaken, you supposed to typed in `node bot.js`
