### ISSUE TITLE
Tutorial still working?

### ISSUE THREAD

**Issue by FlexFM** [renesansz/discord-greeter-bot#38]
Hey! I followed the tutorial on [medium](https://medium.com/@renesansz/tutorial-creating-a-simple-discord-bot-9465a2764dc0) but can't get the bot online? It's added to server ect but it's offline same code as default apart from token.

npm install discord.io winston --save creates a lockfile and warn no licence file/repository field, then go to node bot.js and nothing happens just blank and says C:\Users\Daniel\Discord>

Local machine, node 8.9.3

discord.io@2.5.3
winston@2.4.0
npm -v 5.5.1

I followed the ["Create a test file and run it" hello.js](http://blog.teamtreehouse.com/install-node-js-npm-windows) and it replied Node is installed! in cmd.exe

Cheers!

EDIT: It seems running v6 and installing Git (?) from [axelgreavette's commit](https://github.com/renesansz/discord-greeter-bot/pull/31/files) got the bot online!

**Comment by pikachu292** [comment]
So how did you fix it? I'm having the same problems with the warn repository and licence file.

**Comment by lilcheo** [comment]
@FlexFM and @pikachu292 Just do cd C:\Users\user\directory\folder> and then install it there
