### ISSUE TITLE
Having a problem.... 

### ISSUE THREAD

**Issue by Piflavorz** [renesansz/discord-greeter-bot#39]
Im not exatly sure why, but after i put in `npm install discord.io winston --save`, the only thing that happens whenever i put something relating to bots in the console it responds with `SyntaxError: Invalid or unexpected token`, if I am missing something very obvious please point it out to me.

**Comment by GetOFFMyLAN** [comment]
check to make sure your token is the the same as the one in your app on discord. You may be copying it wrong from discord or may have pasted it wrong in your auth.js folder.
