### ISSUE TITLE
How do you set the game status of the bot?

### ISSUE THREAD

**Issue by n8ventures** [renesansz/discord-greeter-bot#4]
I've been scratching my head to see why it isn't working.

Can you help me?

I tried:
`bot.on('presence', function(user, userID, status, game, event) {
	game: {
		name: "!ping", 
		type: 0
		}
});`

But Type: 0 is an "unexpected token".

This code however,

`bot.setPresence({
	game: {
		name: "!ping", 
		type: 0
}
});`

it completely becomes ignored.

**Comment by Nomad21** [comment]
Add the code inside bot.ready method. 
Example: `bot.on('ready', function(evt){ 
    logger.info("Connected.");
    bot.setPresence({
        game: {
            name: "My Game"
        }
    });
});`

**Comment by lilcheo** [comment]
dosent work
