### ISSUE TITLE
Node.js problem

### ISSUE THREAD

**Issue by qatchy** [renesansz/discord-greeter-bot#40]
Hi, im super new to coding and thought making a discord bot would be a great first project (Maybe it's not that good).  

Im not sure how to navigate inside the folder easily. I can't do it in any way, probably a stupid question but im brand new to this stuff! 
Thanks!

**Comment by kopi-san26** [comment]
i had this problem too, so i seached and you gotta type cd and type the path of the folder.

**Comment by FlexFM** [comment]
Go to the folder's root and hold down Shift and right click "Open command window here" to avoid typing the path every time in command prompt.

**Comment by sarthaktexas** [comment]
exactly! thats what i do! ^^
