### ISSUE TITLE
Opening Command Line?

### ISSUE THREAD

**Issue by Vicas321** [renesansz/discord-greeter-bot#41]
Hi, i followed your guide and it Went pretty well until you had written "Open up your command line and navigate inside the project folder, once you’re in, simply install the dependencies by executing the following command:" I do not know what you mean with this and i would really like some help ASAP.
Thanks

**Comment by sarthaktexas** [comment]
So basically you open up Node.js Command Prompt, then navigate using cd (ex. cd C:/Users/[name of account]/Desktop/discord-greeter-bot-master) then install the dependencies (input the command so the dependencies get installed into the project folder!

**Comment by IceloveandlifeAJ** [comment]
It doesn't seem to want to work for me. I might be doing something wrong tho.
