### ISSUE TITLE
node bot.js aint working

### ISSUE THREAD

**Issue by Slime1234** [renesansz/discord-greeter-bot#42]
node bot.js aint working tried installing everything didnt work, the first the step worked tho.

**Comment by MadMikeyB** [comment]
Looks like the V5 gateway which the `discord.io` npm package was using is deprecated now.

I got the bot working with `npm install woor/discord.io#gateway_v6 --save`

Then I ran `node bot.js` and everything works.

**Comment by Slime1234** [comment]
I did gateway6 .-.

**Comment by TeraTheBotMaker** [comment]
same error buddy, try listing a few screenshots although
