### ISSUE TITLE
Done Everything correctly, bot won't work

### ISSUE THREAD

**Issue by ColePZ** [renesansz/discord-greeter-bot#43]
I put it in and It just comes back with nothing. Help

**Comment by MadMikeyB** [comment]
Looks like the V5 gateway which the `discord.io` npm package was using is deprecated now.

I got the bot working with `npm install woor/discord.io#gateway_v6 --save`

Then I ran `node bot.js` and everything works.

**Comment by kr1stjans** [comment]
Had the same problem. Solved with new dependency. It should be updated on the blog and in the docs.

**Comment by Alexielnoten** [comment]
![image](https://user-images.githubusercontent.com/29492922/37518933-8b10064a-28d4-11e8-862d-323d274969a3.png)
So...now what?
