### ISSUE TITLE
[EDIT: I FIXED IT] when I run node bot.js, nothing happening..

### ISSUE THREAD

**Issue by ItsTauTvyDas** [renesansz/discord-greeter-bot#44]
When I run: node bot.js
nothing happening, why?

**Comment by MadMikeyB** [comment]
Looks like the V5 gateway which the `discord.io` npm package was using is deprecated now.

I got the bot working with `npm install woor/discord.io#gateway_v6 --save`

Then I ran `node bot.js` and everything works.

**Comment by sjcsjc** [comment]
That did not work for me.  I got this error log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'discord.io#gateway_v6',
1 verbose cli   '--save' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose npm-session 7f32bccaed1bdb3f
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose stack Error: Invalid tag name "discord.io#gateway_v6": Tags may not have any characters that encodeURIComponent encodes.
7 verbose stack     at invalidTagName (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:76:15)
7 verbose stack     at fromRegistry (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:265:13)
7 verbose stack     at resolve (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:66:12)
7 verbose stack     at npa (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-package-arg\npa.js:39:10)
7 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:203:14
7 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
7 verbose stack     at Array.forEach (<anonymous>)
7 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
7 verbose stack     at Array.forEach (<anonymous>)
7 verbose stack     at asyncMap (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
7 verbose stack     at exports.getAllMetadata (C:\Program Files\nodejs\node_modules\npm\lib\install\deps.js:200:3)
7 verbose stack     at Installer.loadArgMetadata (C:\Program Files\nodejs\node_modules\npm\lib\install.js:325:3)
7 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:656:16
7 verbose stack     at BB.join.then (C:\Program Files\nodejs\node_modules\npm\lib\install\read-shrinkwrap.js:41:16)
7 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
7 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
8 verbose cwd C:\greeterbot
9 verbose Windows_NT 10.0.15063
10 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "discord.io#gateway_v6" "--save"
11 verbose node v8.9.3
12 verbose npm  v5.5.1
13 error code EINVALIDTAGNAME
14 error Invalid tag name "discord.io#gateway_v6": Tags may not have any characters that encodeURIComponent encodes.
15 verbose exit [ 1, true ]

**Comment by axelgreavette** [comment]
so install Git then run the command

**Comment by Gymlet** [comment]
This worked for me. Thank you!

**Comment by AceTrainerBaileyV2** [comment]
what do you mean "install git"
