### ISSUE TITLE
error at the node bot.js

### ISSUE THREAD

**Issue by kopi-san26** [renesansz/discord-greeter-bot#45]
![image](https://user-images.githubusercontent.com/34898440/34395185-8926e352-eb45-11e7-8a6e-1c666a6374b1.png)

**Comment by MadMikeyB** [comment]
Looks like your auth.json perhaps doesn't have the token in quotes?

**Comment by kopi-san26** [comment]
![image](https://user-images.githubusercontent.com/34898440/34395524-08b51cb8-eb48-11e7-8928-0ea94ff13265.png)

**Comment by kopi-san26** [comment]
how do I fix it?

**Comment by MadMikeyB** [comment]
Add quotes around your token in auth.json?

**Comment by sarthaktexas** [comment]
agreed
