### ISSUE TITLE
Discord bot always online???!!

### ISSUE THREAD

**Issue by TheColdEmeraldCODE** [renesansz/discord-greeter-bot#46]
how can i make my discord bot ALWAYS online??!!

**Comment by wildbook** [comment]
You simply have to have it always running.

**Comment by sarthaktexas** [comment]
ok @TheColdEmeraldCODE you can host it yourself and have it running all the time, OR have a hosting company like heroku run it!

**Comment by axelgreavette** [comment]
Or you can host it on a webpage with it built into the html.
