### ISSUE TITLE
How to add multiple actions into one case command?

### ISSUE THREAD

**Issue by sarthaktexas** [renesansz/discord-greeter-bot#47]

**Comment by axelgreavette** [comment]
Use `If` statements

**Comment by sarthaktexas** [comment]
show me an example please @axelgreavette

**Comment by axelgreavette** [comment]
```
if(command == 'ping') {
bot.sendMessage({
to:channelID,
message: 'pong!'
})
}
```

**Comment by lilcheo** [comment]
@axelgreavette then how do i add the second part

**Comment by axelgreavette** [comment]
the second part? an else statement?

**Comment by sarthaktexas** [comment]
yes. the second part. the `else` statement.

**Comment by Alexielnoten** [comment]
Do you add these commands before or after the break?
![image](https://user-images.githubusercontent.com/29492922/37518530-bef07f00-28d2-11e8-979f-1d0cfb014121.png)

**Comment by axelgreavette** [comment]
lol @Alexielnoten theres a lot of Discord.js in there... you should look into [DualCord](https://npmjs.com/package/dualcord)...
