### ISSUE TITLE
Node bot.js Issue

### ISSUE THREAD

**Issue by Khoco** [renesansz/discord-greeter-bot#48]
I'm new to the whole coding scene and I'm having a battle with the command prompt. When I run node bot.js nothing happens, except the command prompt creates a new line.

**Comment by sarthaktexas** [comment]
can you send a video? maybe you havent coded everything properly?

**Comment by Khoco** [comment]
My bot.js configuration is:
https://pastebin.com/tzN5j0xK

Cmd Prompt output:
![image](https://user-images.githubusercontent.com/21089185/34469048-43b361b6-ef0e-11e7-8af9-f77b783c76eb.png)

**Comment by tiago199988** [comment]
me too

**Comment by RashidUjang** [comment]
From #44, apparently the gateway the discord.io package was using is deprecated. 

If you've installed the discord.io package, you can uninstall it by running the command `npm uninstall discord.io --save`.

Then, install the new package by running the command `npm install woor/discord.io#gateway_v6 --save` and then run it again.

Hope it helps!

**Comment by sirEgghead** [comment]
Perfect answer.  Thanks RashidUjang!

**Comment by cyclonone** [comment]
C:\Users\Stelios\Desktop\discord-greeter-bot-master>npm install woor/discord.io#gateway_v6 --save
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

I get this error after installing new package, any clue? Thanks!

**Comment by RashidUjang** [comment]
@cyclonone Do you have git installed?

**Comment by cyclonone** [comment]
No i dont, i follow the tutorial.

**Comment by RashidUjang** [comment]
@cyclonone You have to have Git installed first to run the commands. Are you using Windows? You can get Git for Windows here https://git-scm.com/downloads

After installing that, try running the command again.

**Comment by SolarZebras** [comment]
Do I need to install Git in a specific filepath? I'm still getting the same error as cyclonone after installing Git on my PC.

**Comment by LilMohong** [comment]
I'm having solarzebra's problem too, any solutions?

**Comment by coranax** [comment]
I was having the same problem as well, so I uninstalled and reinstalled Git. I made a different choice on the "Adjusting your PATH environment" step, which I think is what did it. Initially I had chosen "Use Git from Git Bash only" but the second time chose "**Use Git from the Windows Command Prompt.**" This seemed to do the trick.

**Comment by wiskywalker** [comment]
I installed Git and run it from its terminal and it worked.

**Comment by wwei23** [comment]
It still doesn't work for me.

**Comment by Shadowtail117** [comment]
It worked once when I changed the gateway from 5 to 6, but it hasn't since. I have Git installed on the command line and I'm running `node bot.js` from cmd.
