### ISSUE TITLE
Possible to use spaces in case commands?

### ISSUE THREAD

**Issue by daminrsw** [renesansz/discord-greeter-bot#5]
I want people to be able to command my bot naturally; IE "Bot, do this." where the way to let the bot know starts with "Bot, " (which works fine.) The "do this." however doesn't seem to work, and it's because of the space. Is there a way around this?
![83bd28a1dec0e339f20e24b8dabe9f66](https://user-images.githubusercontent.com/13825026/31851473-2918bfb0-b62c-11e7-836e-81a5e6dcaf84.png)

**Comment by Nomad21** [comment]
```
bot.on('message', function(user, userID, channelID, message, evt){

    if(message.toLowerCase() === "this is my test message"){
        bot.sendMessage({
            to: channelID,
            message: "Testing successful"
        });
    }
});
```
Try this code but I wouldn't recommend this if you have a lot of commands as adding each and every command is tiresome. 

There is an another way to do it but with a bit more complexity. The general idea is to nest switch inside a switch case like
(This is just a pseudo code therefore may not work as it is)
```
switch(cmd[0]){ 
    case 'Bot': 
        switch(cmd[1]){
            case 'do_this':
                // something to do
            break;
    }
}
```
For more flexibility try using [string.includes](https://www.w3schools.com/jsref/jsref_includes.asp) in if statements which can also be [nested](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/if...else).
