### ISSUE TITLE
How do i add playing(name)

### ISSUE THREAD

**Issue by lilcheo** [renesansz/discord-greeter-bot#50]
how do i add that my code is var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
       
        args = args.splice(1);
        switch(cmd) {
            // !ping
            case 'ping':
                bot.sendMessage({
                    to: channelID,
                    message: 'Pong!'
                });
            break;

            case 'lenny':
bot.sendMessage({
to: channelID,
message: '( ͡° ͜ʖ ͡°)'
});

break;
case 'help':
bot.sendMessage({
to: channelID,
message: 'not yet ready'
});

break;
case 'info':
bot.sendMessage({
to: channelID,
message: 'by LilcheoThedog/eevee#5398'
});

break;
case 'coming soon':
bot.sendMessage({
to: channelID,
message: 'help,8ball and bug fixes'
});
break;
            // Just add any case commands if you want to..
         }
     }
});

**Comment by axelgreavette** [comment]
Put this ```bot.setPresence ({
            game:{
                name: GAME NAME,
                type: '1', // can be '2' for 'listening to' prefix // can be '3' for 'watching' prefix
                url: 'URL TO TWITCH IF STREAMING'
            }
        });
    };``` in the ```bot.on('ready', function (evt) {
logger.info('Connected');
logger.info('Logged in as: ');
logger.info(bot.username + ' - (' + bot.id + ')');

PUT IT HERE
});```

**Comment by Valkyy** [comment]
@axelgreavette I tried this and it didn't work. console log:

...\test bot\bot.js:27
          };
         ^
SyntaxError: missing ) after argument list

**Comment by axelgreavette** [comment]
ohh
just remove that one
sorry
i took the code out of my files which its used differently so

**Comment by axelgreavette** [comment]
so this is what your code should look like: 
```
bot.setPresence ({
            game:{
                name: GAME NAME,
                type: '1', // can be '2' for 'listening to' prefix // can be '3' for 'watching' prefix
                url: 'URL TO TWITCH IF STREAMING'
            }
        });
```

**Comment by Valkyy** [comment]
I tried it and the bot logs in, but nothing is displayed :/

**Comment by lilcheo** [comment]
@valkyy just Download a thing i forgot

**Comment by Valkyy** [comment]
@lilcheo what do you mean?

**Comment by sl0zy** [comment]
up
