### ISSUE TITLE
How do i make 8ball

### ISSUE THREAD

**Issue by lilcheo** [renesansz/discord-greeter-bot#51]
plz help i this is my script var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
    logger.info('im awsome')
    logger.info('get a vps u fool')
    
    bot.setPresence ({
        game:{
            name:'Do Prefix !help',
            type: '1', // can be '2' for 'listening to' prefix // can be '3' for 'watching' prefix
        }
    });
});
bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
       
        args = args.splice(1);
        switch(cmd) {
            // !ping
            case 'ping':
                bot.sendMessage({
                    to: channelID,
                    message: 'Pong!'
                });
            break;

            case 'lenny':
bot.sendMessage({
to: channelID,
message: '( ͡° ͜ʖ ͡°)'
});

break;
case 'help':
bot.sendMessage({
to: channelID,
message: '```css do lenny,info,updates.ping.```'
});

break;
case 'info':
bot.sendMessage({
to: channelID,
message: 'by @LilcheoThedog/eevee#5398'
});
break;

case 'Update':
bot.sendMessage({
to: channelID,
message: '**8ball,music**'
});
break;

case 'music':
bot.sendmessage({
to: channelID,
message: 'Coming Soon!!'
});
break;

case '8ball':
bot.sendmessage.random({
to: channelID,
message: 'i dont know try again later,yes,no,Cant understand'
});
break;

default:
bot.sendMessage({ to: channelID, message: 'Unknown command.' });
// Just add any case commands if you want to..
         }
     }
});

and i get this in cmd  G:\my stuff\Discord bot\1\bot.js:82
bot.sendmessage.random({
                ^

TypeError: Cannot read property 'random' of undefined
    at DiscordClient.<anonymous> (G:\my stuff\Discord bot\1\bot.js:82:17)
    at emitMany (events.js:147:13)
    at DiscordClient.emit (events.js:224:7)
    at DiscordClient.handleWSMessage (G:\my stuff\Discord bot\1\node_modules\dis
cord.io\lib\index.js:1811:11)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at Receiver.ontext (G:\my stuff\Discord bot\1\node_modules\discord.io\node_m
odules\ws\lib\WebSocket.js:841:10)
    at G:\my stuff\Discord bot\1\node_modules\discord.io\node_modules\ws\lib\Rec
eiver.js:536:18
    at Receiver.applyExtensions (G:\my stuff\Discord bot\1\node_modules\discord.
io\node_modules\ws\lib\Receiver.js:371:5)
    at G:\my stuff\Discord bot\1\node_modules\discord.io\node_modules\ws\lib\Rec
eiver.js:508:14G:\my stuff\Discord bot\1\bot.js:82
bot.sendmessage.random({
                ^

TypeError: Cannot read property 'random' of undefined
    at DiscordClient.<anonymous> (G:\my stuff\Discord bot\1\bot.js:82:17)
    at emitMany (events.js:147:13)
    at DiscordClient.emit (events.js:224:7)
    at DiscordClient.handleWSMessage (G:\my stuff\Discord bot\1\node_modules\dis
cord.io\lib\index.js:1811:11)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at Receiver.ontext (G:\my stuff\Discord bot\1\node_modules\discord.io\node_m
odules\ws\lib\WebSocket.js:841:10)
    at G:\my stuff\Discord bot\1\node_modules\discord.io\node_modules\ws\lib\Rec
eiver.js:536:18
    at Receiver.applyExtensions (G:\my stuff\Discord bot\1\node_modules\discord.
io\node_modules\ws\lib\Receiver.js:371:5)
    at G:\my stuff\Discord bot\1\node_modules\discord.io\node_modules\ws\lib\Rec
eiver.js:508:14

**Comment by nysean0220** [comment]
Try making the m in bot.sendMessage capital. That may be your problem
