### ISSUE TITLE
n00b here: how to make bot online and run

### ISSUE THREAD

**Issue by serlex00** [renesansz/discord-greeter-bot#52]
Hello! I'm a total n00b, sorry . I have followed the guide but I'm stuck at the MOMENT OF TRUTH, as I don't know how to make my bot online in my server and launch the greeter :(

**Comment by axelgreavette** [comment]
do this: download Git. Then run `npm install woor/discord.io#gateway_v6`. After that installs run `node bot.js` and it should work.

**Comment by brianzhan** [comment]
That doesn't seem to be working for me: https://cdn.discordapp.com/attachments/403062221011419138/403319876199907348/Screen_Shot_2018-01-17_at_4.48.52_PM.png

**Comment by nysean0220** [comment]
Make sure that you didn’t post the secret in auth.json. That’s what got me.

**Comment by Beeblesnout** [comment]
![image](https://user-images.githubusercontent.com/30602106/37070677-b5baa63e-2186-11e8-919f-f37a8490934a.png)
this is the error i get when i run that command in the git CMD

**Comment by nysean0220** [comment]
@Beeblesnout, you forgot the package.json file
