### ISSUE TITLE
Trouble installing dependencies.

### ISSUE THREAD

**Issue by cyropynical** [renesansz/discord-greeter-bot#53]
C:\Users\Cyropynical\Desktop\tumblebot>npm install discord.io winston --save
npm ERR! file C:\Users\Cyropynical\Desktop\tumblebot\package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
 pm ERR! Unexpected token � in JSON at position 0 while parsing near '��{
npm ERR!      " n a m ...'
npm ERR! File: C:\Users\Cyropynical\Desktop\tumblebot\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! Tell the package author to fix their package.json file. JSON.parse

I don't understand what I did wrong. Could someone explain what is happening please?

**Comment by axelgreavette** [comment]
ohh. Just do your Package.json right.

**Comment by axelgreavette** [comment]
can i see the code in you package.json?
