### ISSUE TITLE
How to change the ! command to any text/symbol?

### ISSUE THREAD

**Issue by sl0zy** [renesansz/discord-greeter-bot#55]
});
bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];

**Comment by sarthaktexas** [comment]
```bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it needs to execute a command
    // for this script it will listen for messages that will start with `!`
    if (message.substring(0, 1) == '[change this to whatever you need to]') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];

        args = args.splice(1);

        switch(cmd) {
            // !ping
            case 'ping':
                bot.sendMessage({ to: channelID, message: 'Pong!' });
            break;
            default:
                bot.sendMessage({ to: channelID, message: 'Unknown command.' });
        }```

**Comment by sl0zy** [comment]
@sarthaktexas you're wrong. have you tested it like that?

**Comment by sl0zy** [comment]
for someone want to change it too
);
bot.on('message', function (user, userID, channelID, message, evt) {
// Our bot needs to know if it will execute a command
// It will listen for messages that will start with !
if (message.substring(0, [Number of symbols / letters / numbers]) == '[Change this to whatever you need to]') {
var args = message.substring([Number of symbols / letters / numbers]).split(' ');
var cmd = args[0];
