### ISSUE TITLE
"Invalid or Unexpected Token" - Tried re-generating but doesn't work.

### ISSUE THREAD

**Issue by XxCaptainGxX** [renesansz/discord-greeter-bot#56]
So I followed the steps from one to the next, copying and pasting the code for my test bot until I found my problem here in the npm install discord.io winston --save thing. here's a screenshot.

https://imgur.com/lanmtbV

I tried renewing my token and pasting it into the auth.json file, still the same thing. I'm a total beginner at this, I'd appreciate any help.

**Comment by Hyperynia** [comment]
same with me

**Comment by weeums** [comment]
Same

**Comment by sarthaktexas** [comment]
First of all to start the bot, you do ```node bot.js```. Then go change the gateway from v5 to v6 manually. Then try it.
