### ISSUE TITLE
I can't get my bot online?

### ISSUE THREAD

**Issue by Onyx12** [renesansz/discord-greeter-bot#57]
I just can't get my bot online.
I always get this if i run the command "npm install discord.io winston --save" and "node bot.js": http://prntscr.com/i3jifg

Can someone pls help me??

**Comment by DabatoIsCool** [comment]
Having the same issue here

**Comment by Kemito** [comment]
Onyx12, You have missed the step to create package.json file. It cannot find package.json file in location you are running node command so it cannot save dependencies.

**Comment by CoroNaut** [comment]
I have similar problem about getting the bot online, i insatlled the dependencies to the project folder, and it updated package.json and i ran node bot.js, but still the bot isnt online

**Comment by donkeymonkey1** [comment]
You need auth.json
