### ISSUE TITLE
Issue with the "node bot.js" command?

### ISSUE THREAD

**Issue by ToxxieVG** [renesansz/discord-greeter-bot#58]
Following the guide, I inputted the "npm install discord.io winston --save" command, and then input "node bot.js".

I was greeted by this.
![bot error](https://user-images.githubusercontent.com/35871249/35473247-026e17b6-0375-11e8-9451-420a15e5af62.PNG)

Not 100% certain what's going on here, but I'm getting the feeling that I'm missing something. Anyone got an idea of what's going on?

**Comment by ToxxieVG** [comment]
For reference, here's what I've put inside "bot.js".

![bot error 1](https://user-images.githubusercontent.com/35871249/35473256-46436d56-0375-11e8-8182-7b9ba4c9a022.PNG)

**Comment by moonkit** [comment]
Check if you have right syntax, I can see an error in your code. (line 13)
