### ISSUE TITLE
Bot Wont Run

### ISSUE THREAD

**Issue by Nyctara** [renesansz/discord-greeter-bot#6]
So my bot stopped working, so I changed it back to the example you had
var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt) {
and it wont do anything. No errors, I'll run node  [file] and it'll just go to the next line
C:\Users\Alex>node "C:\Users\Alex\Desktop\Bot\bot.js"

C:\Users\Alex>
Any ideas?

**Comment by renesansz** [comment]
Can you compare your bot.js with mine?
https://github.com/renesansz/discord-greeter-bot/blob/master/bot.js

**Comment by Nyctara** [comment]
Mine
var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
colorize: true
});
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
token: auth.token,
autorun: true
});
bot.on('ready', function (evt) {
logger.info('Connected');
logger.info('Logged in as: ');
logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt) {
Yours
var Discord = require('discord.io');

var logger = require('winston');
var auth = require('./auth.json');


// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';


// Initialize Discord Bot
var bot = new Discord.Client({
    token: auth.token,
    autorun: true
});


bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});

bot.on('message', function (user, userID, channelID, message, evt) {

**Comment by Nomad21** [comment]
My best guess is you are missing a semicolon somewhere :). If its not to much trouble can you make a [gist](https://gist.github.com) and share it here?
