### ISSUE TITLE
Can't get my bot online? Node bot.js is unexpected identifier?

### ISSUE THREAD

**Issue by stainedmiles** [renesansz/discord-greeter-bot#60]
Node keeps telling me that "node bot.js" was an unexpected identifier. I'm new to coding like this, but have slight experience, so send help if you can. Also says that it is syntax?

**Comment by stainedmiles** [comment]
It also says that it's a syntax error.

**Comment by stainedmiles** [comment]
![send help](https://user-images.githubusercontent.com/35909533/35493365-3789d3e6-0478-11e8-873d-b476198c2cce.PNG)

**Comment by donkeymonkey1** [comment]
Maybe u don't have auth.json

**Comment by narFnarF** [comment]
On your screenshot, it seems you started node by typing "node" alone, so now it's running and you can't type the other commands inside of it. You need to exit Node first.

To exit Node, I think you need to press Ctrl+ D, or maybe it's Ctrl+C
I'm not sure. Try both.
