### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by asmbre04** [renesansz/discord-greeter-bot#61]
I am having some problems with the installations of the bot in cmd. I am new to programing and having some troubles with understanding cmd. Can i get some help
![skjermbilde](https://user-images.githubusercontent.com/35918591/35505190-9c638e5c-04e5-11e8-92a7-321a76a2c1ba.PNG)

**Comment by didinele** [comment]
Alrigty, I had the same issue and I figured it out myself, since im not very good at explaining this is the article that helped me out. https://www.digitalcitizen.life/command-prompt-how-use-basic-commands

**Comment by asmbre04** [comment]
Thank you a lot for this, this will help me a lot with my bot
