### ISSUE TITLE
node bot.js does not work after reviewing all issues from the past 4 months

### ISSUE THREAD

**Issue by pupperpowell** [renesansz/discord-greeter-bot#66]
I have an auth.json with token, a bot.js, a package.json, Git installed, discord.js, winston, and that woor/discord.io#gateway_v6 one. When I say "node bot.js" without quotes, this appears

![image](https://user-images.githubusercontent.com/34691200/36082480-d7162568-0f77-11e8-9ff5-6c87de9adc78.png)

Am I missing something obvious?

**Comment by Laks0** [comment]
Same, please someone answer

**Comment by Dalekkar** [comment]
i have the exact same problem, anyone able to help?

**Comment by VanWrath** [comment]
Are you running the command in the same directory where the bot.js file is in? Use "dir" command to check if you see bot.js in the directory.
