### ISSUE TITLE
Nothing happens when I run "node bot.js"

### ISSUE THREAD

**Issue by TyCooper8** [renesansz/discord-greeter-bot#70]
Everything goes smoothly throughout [the tutorial](https://medium.com/@renesansz/tutorial-creating-a-simple-discord-bot-9465a2764dc0) but then the final step doesn't seem to do anything. I input it, press enter, and nothing happens. The bot won't go online.

**Comment by qgoutte** [comment]
discord.io is deprecated you need see this #48
