### ISSUE TITLE
How to get the bot online (mobile) 

### ISSUE THREAD

**Issue by KahjitAce** [renesansz/discord-greeter-bot#74]
I'm a complete noob at this but wanted to see if you can do this on a phone.. Android. So I have both auth.json and bot.js but when I enter npm install bot.js it gives me errors:
Error: Cannot find module '/data/data/com.termux/files/home/bot.js'
    at Function.Module._resolveFilename (module.js:538:15)
npm WARN saveError ENOENT: no such file or directory, open '/data/data/com.termux/files/home/package.json'
npm WARN enoent ENOENT: no such file or directory, open ''/data/data/com.termux/files/home/package.json'
npm WARN discord.js@11.3.0 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of libsodium-wrappers@^0.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.0 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN home No description
npm WARN home No repository field.
npm WARN home No README data
npm WARN home No license field.

+ bot.js@0.0.1
updated 1 package in 1.964s

Not sure what it all means but my bot is still not online. I saw something about git too and tried downloading an app called fast hub where I made a new git but I'm not sure where to go from there.

**Comment by sarthaktexas** [comment]
### Try `npm install [dependency here]`.
_ex. `npm install discord.js`_
