### ISSUE TITLE
npm WARN saveError ENOENT: no such file or directory, open 'C:/Users/NAME/package.json'

### ISSUE THREAD

**Issue by Serkets** [renesansz/discord-greeter-bot#77]
I never did this kind of things before, so I followed every single step of the tutorial - or at least, I think so.
But when I type "npm install discord.io winston --save", I get an error message (see screenshot). 
What can I do? 
I even tried to solve it by typing "npm install" and hit Enter, and since the problem was still there, I typed "npm cache clean" and hit Enter. This is what I get.

Note: I created a folder named _greeter-bot_ on my desktop and then put in the files _package.json, auth.json_ & _bot.js_ 

I used Nodejs v9.6.1 for Windows (x64)

![cmd](https://user-images.githubusercontent.com/36938487/36819363-8990b70c-1ce9-11e8-9b57-fc1bc3dd278c.png)

**Comment by sarthaktexas** [comment]
It looks like your missing text fields in `package.json`. Specifically, either don't have the file saved, or missing the field shown (probably not the case).

**Comment by Serkets** [comment]
I tried even by moving the three files (_package.json, auth.json & bot.js_) in C:/Users/Alessia, with and without them being into the _greeter-bot_ folder. Still not working.

Is there a specific path to put them?

**Comment by sarthaktexas** [comment]
Did you do this?  `npm install discord.io winston --save`

**Comment by sarthaktexas** [comment]
`
{
  "name": "greeter-bot",
  "version": "1.0.0",
  "description": "My own Discord bot",
  "main": "bot.js",
  "author": "Alessia",
  "dependencies": {}
}`

**Comment by sarthaktexas** [comment]
[discordchatbot.zip](https://github.com/renesansz/discord-greeter-bot/files/1773428/discordchatbot.zip)
Try that! ^^

**Comment by Serkets** [comment]
I've sent you a mail since I can't add you on discord :< 
Anyway, for what I understood, I should input the command `npm install discord.io winston --save` in cmd.exe and not in Notejs.exe.

By the way, I tried to input it in notejs anyway, didn't work 
![nodejs](https://user-images.githubusercontent.com/36938487/36916247-adaa0088-1e53-11e8-8c2c-1ed6a6db9d80.png)
