### ISSUE TITLE
[Solved] One command stack up with others.

### ISSUE THREAD

**Issue by hellobafu** [renesansz/discord-greeter-bot#78]
The bot works fine, but the 'inv' command executes above or under the other commands
when they're executed.
This is (a part of) my code without the tabs in front of the cases:
birih = but I removed it here (for my privacy).

-----
```js

case 'brname':
    bot.sendMessage({
        to: channelID,
        message: '`<my name on Fortnite, birih>`. That is correct, eh, <my discord id, birih>?'
    });

// My custom !ping.
case 'moffa':
    bot.sendMessage({
        to: channelID,
        message: 'MOFFA!'
    });

// Sends invite.
case 'inv':
    bot.sendMessage({
        to: channelID,
        message: 'Try this link: <link to my discord, birih>'
    });

break;
```
-----

Here's an [image](https://imgur.com/a/kXLm2).
I am 'hux', and my bot is 'K-3PO'.

As you see, when I execute the two commands that aren't 'inv', I get the command 'inv'
on top (or under) the command I really wanted.
I can't see anything wrong with the code, so I'm open to fixes.

**EDIT: I had to put `break;` in between each case.**

**Comment by PedrolinoV2** [comment]
How did you fix it? I dont know much JS, and I try to avoid thinking that it is just like java
