### ISSUE TITLE
Node.js issue

### ISSUE THREAD

**Issue by GreyOkami1998** [renesansz/discord-greeter-bot#8]
I followed your examples to the dot and checked them numerous times, but when I try to install the node library, I get a syntax error. 
![image](https://user-images.githubusercontent.com/33080048/31980672-15c0bcb8-b91c-11e7-9e89-d3c5c7314aa1.png)
Every time I check the token it's different, so I update it in the command line, and still get an error. 
![image](https://user-images.githubusercontent.com/33080048/31980736-952d4782-b91c-11e7-9573-af70d1f91a86.png)
Thank you for your time.

**Comment by Nomad21** [comment]
Can you post your error log?. Also are you typing out the directory path? looks like the error is related to the path.

Cheers
