### ISSUE TITLE
cant install dependencies

### ISSUE THREAD

**Issue by Beeblesnout** [renesansz/discord-greeter-bot#83]
![image](https://user-images.githubusercontent.com/30602106/37070722-e9123506-2186-11e8-8697-51d9b5e1a7b8.png)
I'm using the npm install woor/discord.io#gateway_v6 --save command (not the deprecated one) and I get this error each time. I'm using the Git Comand Prompt thing too

**Comment by nysean0220** [comment]
You need a package.json file as well. It's claiming you missed it
