### ISSUE TITLE
BOT where is it ? 

### ISSUE THREAD

**Issue by PveOnly** [renesansz/discord-greeter-bot#84]
Hi so i copied your code and pasted it and when i launch my discord bot 
![image](https://user-images.githubusercontent.com/37158659/37116896-de14014c-224f-11e8-889a-3b242c8038a0.png)

Nothing is happening , he's not on my discord channel so i don't really understand where is it ? Did i forget something ? Thx

**Comment by PveOnly** [comment]
![image](https://user-images.githubusercontent.com/37158659/37155677-2372bc4e-22e4-11e8-9dda-c27bf39b52bf.png)
![image](https://user-images.githubusercontent.com/37158659/37155886-c4bacdd0-22e4-11e8-9634-f70a850a6c44.png)

btw when i said "copy pasted code " i literraly did it so except the "YOUR BOT TOKEN" that i changed with my bot token all the code is the same so i guess it's where the problem lies but i don't know what i need to change. Is there specific information i need to write in this code or it should word with this code ?

**Comment by orkc** [comment]
I am having the same issue.

**Comment by PveOnly** [comment]
Hi orkc did you copy pasted like me or you changed somethings in the code ? (except the bot token)
(will try ur solution btw thx)
