### ISSUE TITLE
Nothing happens after node bot.js

### ISSUE THREAD

**Issue by Laks0** [renesansz/discord-greeter-bot#87]
I execute the command and nothing happens, I installed all packages but nothing.

**Comment by HudsonGraeme** [comment]
Did you add the bot to your server?

**Comment by SquibbleQuibble** [comment]
I had the same issue, bot is connected to server. Wont go online, executing command does nothing.

**Comment by UnsignedByte** [comment]
Yeah i'm having the same error. creating the bot works but it's still offline.
Printing Bot gives me:

<img width="222" alt="screen shot 2018-03-20 at 07 15 26" src="https://user-images.githubusercontent.com/34429084/37659944-80fb04e2-2c0e-11e8-917e-f21820d6b035.png">

**Comment by AceTrainerBaileyV2** [comment]
Same here. Would really appreciate an answer to this. Rather not wait days to get this fixed

**Comment by Kaikina** [comment]
Same :/

**Comment by Nameless9** [comment]
same
