### ISSUE TITLE
When I enter "node bot.js" I get errors and the bot is ofline.

### ISSUE THREAD

**Issue by WildVortex45** [renesansz/discord-greeter-bot#88]
When I eneter "node bot.js" into the node.js command prompt, I get lots of errors. Also, in my server, the bot is offline. This is what is says in node.js when I enter the command:

C:\Max\Code\discordbot\test\node_modules\winston-transport\legacy.js:17
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (C:\Max\Code\discordbot\test\node_modules\winston-transport\legacy.js:17:11)
    at DerivedLogger.add (C:\Max\Code\discordbot\test\node_modules\winston\lib\winston\logger.js:277:7)
    at Object.winston.(anonymous function) [as add] (C:\Max\Code\discordbot\test\node_modules\winston\lib\winston.js:84:34)
    at Object.<anonymous> (C:\Max\Code\discordbot\test\bot.js:6:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

Please help!

**Comment by Gaberoll** [comment]
I'm getting the same thing, it seems to be failing when it hits logger.add(logger.transports.Console...

**Comment by HudsonGraeme** [comment]
Having the same issue. Looking at the Winston API, something like:

```
logger.add(new logger.transports.Console, {
colorize: true
});
```
Fixes the error, however it does not affect the offline state of the bot

**Comment by IliyanPlIvanov** [comment]
@HudsonGraeme sadly that did not fixed it for me

**Comment by HudsonGraeme** [comment]
@IliyanPlIvanov What happens now? Does it still show the error?

**Comment by andmit** [comment]
WORKS!!!

**Comment by jylescoad-ward** [comment]
before doing the solution that @HudsonGraeme put up in his edit, install git to $PATH here: https://git-scm.com/downloads

**Comment by Tostadora1** [comment]
> Having the same issue. Looking at the Winston API, something like:
> 
> ```
> logger.add(new logger.transports.Console, {
> colorize: true
> });
> ```
> Fixes the error, however it does not affect the offline state of the bot
> 
> EDIT: Run the below and it should work ;)
> `npm install discord.io github:woor/discord.io#gateway_v6 winston --save`
> Author: @orkc #84

before running the npm command you need to install git and add it to your path but this worked perfectly thanks!

**Comment by TizwigTFC** [comment]
I also get errors with my bot offline. but i get these:
![image](https://user-images.githubusercontent.com/25492840/50129769-88f26a80-0248-11e9-8bcb-195bfb52b1b7.png)

**Comment by 324Luke** [comment]
@TizwigTFC  Simply add a `\` before the `'` and you should be fine.

**Comment by Yonton** [comment]
Ive downloaded git but am still getting the same error


$ node bot.js                                                                    internal/modules/cjs/loader.js:711                                                   throw err;                                                                       ^                                                                                                                                                             SyntaxError: C:\Users\Nick\Desktop\DiscordBot\auth.json: Unexpected token � in J SON at position 3                                                                    at JSON.parse ()                                                      at Object.Module._extensions..json (internal/modules/cjs/loader.js:708:27)       at Module.load (internal/modules/cjs/loader.js:599:32)                           at tryModuleLoad (internal/modules/cjs/loader.js:538:12)                         at Function.Module._load (internal/modules/cjs/loader.js:530:3)                  at Module.require (internal/modules/cjs/loader.js:637:17)                        at require (internal/modules/cjs/helpers.js:22:18)                               at Object. (C:\Users\Nick\Desktop\DiscordBot\bot.js:3:12)             at Module._compile (internal/modules/cjs/loader.js:689:30)                       at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
--
