### ISSUE TITLE
Bot will not be found in the folder [SOLVED]

### ISSUE THREAD

**Issue by EnderRifter** [renesansz/discord-greeter-bot#9]
Turns out that one cannot trust notepad ++ to assign the correct file suffix.

whenever i type node bot.js, i get the following error message:
C:\=PATH=\Bot Stuff>node bot.js
module.js:515
    throw err;
    ^

Error: Cannot find module 'C:\=PATH=\Bot Stuff\bot.js'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

I have installed all the necessary files into the folder the bot is in (i have triple checked this ). I have also made sure that the file bot.js is in the folder as well.
I am running Node version 8.8.1

My bot code:
var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
       
        args = args.splice(1);
        switch(cmd) {
            // !ping
            case 'ping':
                bot.sendMessage({
                    to: channelID,
                    message: 'Pong!'
                });
            break;
            // Just add any case commands if you want to..
         }
     }
});

**Comment by renesansz** [comment]
Good to know you were able to resolve the issue by yourself.
Closing ticket now.
