### ISSUE TITLE
Trouble installing NPM

### ISSUE THREAD

**Issue by Alexielnoten** [renesansz/discord-greeter-bot#91]
So, I tried to install dependencies, and got an error, so I went back and fixed those errors, but when I tried again to install dependencies...I started getting these errors.
![image](https://user-images.githubusercontent.com/29492922/37512600-d5fb82ca-28bf-11e8-92b4-403b99bddbc4.png)
And now I don't know what to do.  Everything I see on here is for different types of errors, or link to pages routing folders that...I kinda aren't looking at.  Can anyone help?

**Comment by Alexielnoten** [comment]
Update, I did also use the updated .io installation
![image](https://user-images.githubusercontent.com/29492922/37523669-e49e9d92-28e4-11e8-80c8-dbd441df49d0.png)
and continue to receive the same error.

**Comment by jylescoad-ward** [comment]
Goto the folder where your bot.js and other javascript files are.
After this your command prompt should look like this 
https://gyazo.com/60f61ef0e4508757fab65e9ba3fdcf76

**Comment by VanWrath** [comment]
You have to manually change the directory to where your bot.js file is. Use the command cd to change the directory.
![cmd](https://user-images.githubusercontent.com/31023745/37552723-f04bb6fa-2990-11e8-9071-8d899a8b4c01.PNG)

You don't need to install discord.io. You just need woor/discord.io#gateway_v6 and winston.
Hope this helps
