### ISSUE TITLE
Node bot.js isnt working

### ISSUE THREAD

**Issue by Ivankens** [renesansz/discord-greeter-bot#93]
WHen i try to bring the bot online i get an error
[error.docx](https://github.com/renesansz/discord-greeter-bot/files/1829624/error.docx)

**Comment by Mrthomas20121** [comment]
it doesn't work because you don't have the last version of discord.io. discord switched to the v6 api and the script isn't working well. use this one npm install https://github.com/woor/discord.io/tarball/gateway_v6
