### ISSUE TITLE
"node bot.js" Does Nothing

### ISSUE THREAD

**Issue by WarWeazel** [renesansz/discord-greeter-bot#95]
As the title says, when I enter the command node bot.js nothing happens. I know Discord.io gatewayv5 is depreciated, but even after updating to v6 nothing changes.

![image](https://user-images.githubusercontent.com/37630577/37732044-34d55db2-2d1a-11e8-8d06-650c4fe4a062.png)

The files bot.js, package.json, and auth.json are as they come in the tutorial, save for the ticket.

**Comment by Last2Night** [comment]
Same problem.

**Comment by gregoryj17** [comment]
I was having the same problem, but Issue #48 solved it for me. Try that.

**Comment by lucasknook** [comment]
Go in the nodes folder (if I am correct that is the name xD) ant then go in lib, edit the .js file that is in there and change the gatway from 5 to 6, then save and try again.

**Comment by AceTrainerBaileyV2** [comment]
lucasknook which .js file in >lib ? there are lots of them.

**Comment by lucasknook** [comment]
Oh, weird, I only have one, it should be index.js.

**Comment by MacaylaMarvelous81** [comment]
I'm having the same problem. I tried using Issue #48, but it didn't work. node bot.js still does nothing.

**Comment by rainy-goose** [comment]
@AceTrainerBaileyV2 
I got it working by doing this:
Go to \node_modules\discord.io\lib and changing GATEWAY_VERSION to 6 instead of 5. I hope this helps!

**Comment by leaglem** [comment]
I found the index.js in the lib and the gateway was already set to 6. It's still not working.

**Comment by robkle** [comment]
I also did something dumb and got this problem. After doing everything that I could find here I noticed something: you've got 2 secret thingies on the discord app page. the secret client and the bot token. I had previously entered the secret client string. yeah, dis no work. 

Check if you did the same, ifso change it to the bot token string.
