### ISSUE TITLE
I need the bot to return a member count and on another command, a list of members in the server

### ISSUE THREAD

**Issue by sarthaktexas** [renesansz/discord-greeter-bot#98]
I need the bot to return a member count and on another command, a list of members in the server. How do I do it?

**Comment by axelgreavette** [comment]
Member count you could do with the following chuck of code:
`bot.servers[bot.channels[channelID].guild_id].members.length`
and a Member list would be something similar, however I don't know it exactly.... You may want the get help from the [Discord.io Support Guild](https://discord.gg/pHcq66n) for that part
