### ISSUE TITLE
make the bot answer something different if a specific user calls it

### ISSUE THREAD

**Issue by IchigoDemandsFurryBoobs** [renesansz/discord-greeter-bot#99]
i'd like to make my bot post a "working?" when any user except me types "test" and say "working0?" when i type "test", the bot goes online perfectly but at the moment when i type "test" the bot says "working?" and node.js says that it can't read properly "toLowerCase", the script i'm using is the following:
```javascript
var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt)
{
    {
	if (message.toLowerCase() == "test")
        {
               console.log("test");
                bot.sendMessage({
                    to: channelID,
                    message: "working?"
                });
}
	else
		if (userID == "%user ID%".message.toLowerCase() == "test")
		{
               console.log("test0");
                bot.sendMessage({
                    to: channelID,
                    message: "working0?"
                });
}
	    }
});
```
i known, i couldn't suck more at javascript but meh

**Comment by max214878** [comment]
Try this, it should work as long as the bot.sendMessage you provided normally works. The order you tested the conditions in is wrong, since the message will match "test" even if it's you sending it so the program won't bother checking the else statement 

Get your user ID by typing `\@<yourusername>` in any chat channel and swap it in where I've put <yourID>.

    if (message.toLowercase() == "test") { // if the message says "test"
        if(userID == "<yourID>") { // ...and it is sent by you
            console.log("test0"); // log test0
            bot.sendMessage({ // send working0
                to: channelID,
                message: "working0?" }); 
        else { // if the message says "test" but *isn't* sent by you
            console.log("test"); // log test
            bot.sendMessage({  // send working
                to: channelID,
                message: "working?" }); }
    }

I also don't have a huge amount experience in js but I tried my best with what you provided :)

**Comment by IchigoDemandsFurryBoobs** [comment]
k that works thx but i want to also have blank spaces, i tried this
```javascript
bot.on('message', function (user, userID, channelID, message, evt) {
	    if (message.substring(0, 1) == 'test ') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
       
        args = args.splice(1);
        switch(cmd) {
            case "0 1":
				if (userID == "<userID>") {
					bot.sendMessage({
						to: channelID,
						message: "working?" }); }
				else {
					bot.sendMessage({
						to: channelID,
						message: "working?0" }); }
            break;
         }
	}
});```
